### PR TITLE
Store Contact.pubkey as string

### LINKED ISSUE #3247: replace `Key` in `Contact` for better consistency
@tomholub We also wanted to replace `Key` in `Contact` with another type, so we calculate `usableForEncryptionButExpired` etc. at the moment of loading.

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/issues/3220#issuecomment-743785530_

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Closes #3247

### CODE REVIEW

**Comment by rrrooommmaaa** [comment]
@tomholub Does this look good for consistent keeping of `pubkey` as strings in the database, and re-parsing on load for keys that are currently saved as `Key`?

**Review by tomholub — APPROVED** [review]
I think so, looks good to me

**Comment by tomholub** [comment]
Let me know once ready to merge

**Comment by rrrooommmaaa** [comment]
@tomholub I would suggest to create `ContactPreview` refactoring in this PR, but as you requested it in a separate PR, let's merge this.

**Pull request merged**
