### PR TITLE
Align focused state of action buttons with their hover state

### LINKED ISSUE #1906: Controls in Secure Compose Window should be tab-friendly and indicate the focused state
Some people prefer not to touch their mouse/trackpad and use a keyboard for navigating fields, buttons and other controls:

Peek 2019-08-12 12-19

In Secure Compose Window I can't always see which element is currently focused, all these buttons aren't accessible with a keyboard:

image

### PR DESCRIPTION
**Pull request by limonte**
Closes #1906

Replaced action `<div>`s with `<button>`s with appropriate `tabindex`es so they are focusable and clickable with keyboard (Enter or Space).

What I wasn't able to achieve is to trigger file upload dialog with the keyboard. By hitting Space or Enter the button is getting clicked, not the `<input>` inside it. @tomholub Do you maybe have any hint which could help here?

### CODE REVIEW

**Comment by tomholub** [comment]
Sorry, I don't have many hints for that. We use fine-upploader which does some magic with a checkbox, I think. I forgot what exactly was it doing tbh. We could address that sometime in the future, it's possible we will one day deprecate fine-upploader.

**Comment by limonte** [comment]
> it's possible we will one day deprecate fine-upploader.

It is deprecated (archived) already. So, it makes sense to use something else in the future.

**Comment by tomholub** [comment]
Yes. But it works well for now, so we'll see. Eventually.

**Comment by tomholub** [comment]
Testing this, I found another issue: tab all the way to the `footer`, then enter, then escape - whole window goes away - not good.

**Comment by limonte** [comment]
> Testing this, I found another issue: tab all the way to the footer, then enter, then escape - whole window goes away - not good.

I'll address that in scope of this PR :+1:

**Comment by tomholub** [comment]
Ah, ok, I'll close both #1955 and #1906 when this merges. Thanks!

**Comment by limonte** [comment]
> Testing this, I found another issue: tab all the way to the footer, then enter, then escape - whole window goes away - not good.

whole window is not going away now, but Esc isn't closing the footer modal, even though `closeOnEsc` is `true` by default. I believe the reason for that is iframe inside featherlight and the `keydown` events aren't bubbling to featherlight handlers.

**Comment by limonte** [comment]
@tomholub should we change #1955 to "Esc isn't closing footer modal"?

**Comment by tomholub** [comment]
Can

**Pull request merged**
