### PR TITLE
[WIP] Remove storing drafts metadata into local storage

### LINKED ISSUE #2151: re-working drafts without local storage + drafts don't work from other device
#920

### PR DESCRIPTION
**Pull request by limonte**
Closes #2151 

~~Drafts seem to work fine after removing this code, tests are passing + tested manually.~~

Reply drafts aren't working.

### CODE REVIEW

**Comment by limonte** [comment]
There's still code to remove.

**Comment by limonte** [comment]
Even though tests are passing, this actually breaks reply drafts. I'll keep this draft opened so I can write the test case which proves that the removed code is actually needed. Then I'll revert the removed code.

**Comment by tomholub** [comment]
> Even though tests are passing, this actually breaks reply drafts. I'll keep this draft opened so I can write the test case which proves that the removed code is actually needed. Then I'll revert the removed code.

That's a good approach.

But after writing the test, instead of reverting removed code, can you see if there is any way we can actually do without the local storage for drafts? Maybe by getting the necessary information from Google API instead?

**Comment by limonte** [comment]
> But after writing the test, instead of reverting removed code, can you see if there is any way we can actually do without the local storage for drafts? Maybe by getting the necessary information from Google API instead?

Yes, I'll try that in another PR which will actually resolve #2151

**Comment by tomholub** [comment]
Got it :+1:

**Pull request closed without merging**
