### PR TITLE
Fixes mobile table bugs on subscribe and backup pages

### PR DESCRIPTION
**Pull request by mondo989**
sep-03-2018 13-30-04

### CODE REVIEW

**Comment by mondo989** [comment]
screen shot 2018-09-03 at 3 35 53 pm
screen shot 2018-09-03 at 3 35 03 pm

**Comment by mondo989** [comment]
Should address issue #1247

**Comment by tomholub** [comment]
Great! The Contacts look a bit awkward, maybe we should start using icons for the actions and put them all on one line. That would be for another issue.

**Comment by mondo989** [comment]
Sounds good to me, just wanted to get them responsive :)

**Comment by mondo989** [comment]
@tomholub Will address the 'Contacts' by this weekend.

**Pull request merged**
