### PR TITLE
allow spinner image on gmail page

### LINKED ISSUE #5196: Spinner isn't displayed on gmail page
Current behavior:

image

Should be:

image

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
This PR allows the spinner image to be visible on gmail page
(actually allows hrefs to extension's resources)

close #5196

----------------------------------

**Tests** _(delete all except exactly one)_:
- Not worth testing?

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by rrrooommmaaa** [comment]
Perhaps we can add some CSS related to spinners to `webmail.css`?

This is how it looks now:
image

**Comment by sosnovsky** [comment]
> Perhaps we can add some CSS related to spinners to `webmail.css`?

Yes, it'll look better if icon will be aligned with text, as currently it's too high:

Screenshot 2023-05-29 at 16 43 15

**Review by sosnovsky — DISMISSED** [review]
Looks good 👍

**Comment by sosnovsky** [comment]
Updated:

Screenshot 2023-05-29 at 17 07 23

**Pull request merged**
