### PR TITLE
Add ESLint indent rule

### LINKED ISSUE #2330: eslint rule two space indent
https://eslint.org/docs/rules/indent to run in the CI

This way we'll make sure that code was auto-formatted before it was checked in, prevent messiness.

Also some of my regex-linters expect a two-space indent, and don't work when using a 4-space.

### PR DESCRIPTION
**Pull request by limonte**
Closes #2330

Docs: https://eslint.org/docs/rules/indent

I was planning to use [`@typescript-eslint/indent`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md), but unexpectedly I wasn't able to configure this unwanted behavior:

image

That's why I decided to use the native eslint's  `indent` rule.

PRO tip: add `"eslint.autoFixOnSave": true,` to VSCode settings to delegate routine fixes to robots.

### CODE REVIEW

**Comment by limonte** [comment]
@tomholub that's a flaky test, failing in master as well.

**Comment by tomholub** [comment]
> @tomholub that's a flaky test, failing in master as well.

I'll address & fix these, thanks!

**Comment by tomholub** [comment]
> PRO tip: add "eslint.autoFixOnSave": true, to VSCode settings to delegate routine fixes to robots.

I was hoping there is something like that, let's add it to workspace settings

**Comment by limonte** [comment]
> > PRO tip: add "eslint.autoFixOnSave": true, to VSCode settings to delegate routine fixes to robots.
> 
> I was hoping there is something like that, let's add it to workspace settings

Good idea, done!

**Pull request merged**
