### PR TITLE
Flaky gmail test for encrypted drafts: make sure there's no drafts before running this test

### LINKED ISSUE #3481: Flaky test - secure reply btn, reply draft
Okay, I reran the tests for the last commit to master (which passed when the commit was merged) and they are now failing: https://flowcrypt.semaphoreci.com/workflows/9ba160ab-2172-4a99-85ca-234edf401adc?pipeline_id=320a823f-bbcf-41db-8052-d2f11c0bbe7f

So I don't believe this is related to this PR specifically.

_Originally posted by @seisvelas in https://github.com/FlowCrypt/flowcrypt-browser/issues/3480#issuecomment-796663205_

### PR DESCRIPTION
**Pull request by limonte**
This PR is another attempt to fix the flaky Gmail test.

close #3481

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by limonte** [comment]
@tomholub I just realized that the issue might be in parallelizing tests. If two instances of Gmail live tests are running simultaneously, then there are chances that something will collapse. E.g. this particular test case running in two parallel instances will fail.

Do you think we should limit the parallelization in CircleCI? Maybe there's even an option to prevent parallelization only for particular jobs (live Gmail tests in our case). Let me know your thoughts on this.

**Comment by limonte** [comment]
> However, is there parallelism across PRs? That's possible, it's hard to say.

Yes, there is parallelism across PRs.

> If it's just a single tests that's giving us disproportionate amount of trouble, we may want to disable that tests, I guess.

The flaky test is quite useful, it covers creating, saving, and sending the encrypted drafts which is the important part of FlowCrypt. Let me play a bit more with it, I'll make it robust.

**Comment by tomholub** [comment]
understood - thanks!

**Review by tomholub — APPROVED** [review]
Thanks!

**Pull request merged**
