### PR TITLE
#2649 Google OAuth OOB migration (Using chrome.identity)

### LINKED ISSUE #2649: stop using urn:ietf:wg:oauth:2.0:oob:auto before Oct 3
> Any reason why the OAuth to Google uses "Programmatic extraction urn:ietf:wg:oauth:2.0:oob:auto" ? The docs from Google says this option is deprecated and should only be used for embedded browsers/web views

> Google OAuth does provide a way to pass OAuth token via postMessage or other safer means

https://cure53.slack.com/archives/GSMB8RGFK/p1583983921015100

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR implemented Google OAuth OOB migration

close #2649 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
This is great, you have basically done it. The rest is cleanup work :-)

> New OAuth popup is not recognized by puppeteer. and all puppeteer tests fail.

Got it, that should be fixable

> With our new OAuth popup, google displays optional checkbox in consent screen like below.
> We might check if permission is allowed in each screen and ask user to allow permission but that might be a huge change.

Indeed that would be too much work, for now. However, we already do this for `Contacts`. Therefore you can ignore missing contacts permission, it's optional during setup.

> So my suggestion is to display error(info) popup when there are missing scopes user didn't check in login screen.
Something like, we need xxx permissions to allow you to do xxx. would you like to try again & allow consent?
And then show consent screen again (this time, checkboxes are not showing as user previously allowed basic scopes)
What do you think?

We've had this situation on iOS. I think the fix should be the same. It's pretty much what you said. Following a successful but incomplete authorization, you can implement it with a modal that says the same thing as we did in iOS, it was something like "This worked, now please also  ..." and when user clicks "ok", show another authorization. Just copy the text and buttons from iOS.

> Also as we save & restore scopes through AcctStore, contact search scope was set as true(even though user doesn't check contact search consent) and contact search api returns 403 error.

Maybe it wasn't such a good idea to keep this in `AcctStore`. It can get out of sync. Is there a Google endpoint where we can figure out current authorizations? Otherwise, any ideas?

**Comment by ioanmo226** [comment]
I totally agree. I think there might be functionality to check authorized scopes in web too as we did successfully in iOS app.
By the way, I think better to do this in another task as this one is big enough task.
> Maybe it wasn't such a good idea to keep this in AcctStore. It can get out of sync. Is there a Google endpoint where we can figure out current authorizations? Otherwise, any ideas?

**Comment by tomholub** [comment]
> I totally agree. User might remove it manually from google account page and it can get out of sync easily. I think there must be functionality to check authorized scopes in web too as we did successfully in iOS app. By the way, I think better to do this in another task as this one is big enough task.
> 
> > Maybe it wasn't such a good idea to keep this in AcctStore. It can get out of sync. Is there a Google endpoint where we can figure out current authorizations? Otherwise, any ideas?

On iOS, the client library does that. It's possible they investigate the response from the authorization endpoint, or maybe it's a separate call. You could investigate the library source to find out.

**Comment by ioanmo226** [comment]
Yeah, sure :-)

**Comment by tomholub** [comment]
> I totally agree. User might remove it manually from google account page and it can get out of sync easily. I think there must be functionality to check authorized scopes in web too as we did successfully in iOS app. By the way, I think better to do this in another task as this one is big enough task.
> 
> > Maybe it wasn't such a good idea to keep this in AcctStore. It can get out of sync. Is there a Google endpoint where we can figure out current authorizations? Otherwise, any ideas?

Sure, if a workable solution can be achieved without removing this, then we should indeed leave that for another day.

**Comment by tomholub** [comment]
closing in favor of https://github.com/FlowCrypt/flowcrypt-browser/pull/4665

**Pull request closed without merging**
