### PR TITLE
Send email by ctrl+enter only when focus is in subject or compose

### LINKED ISSUE #2434: Increase min-height of pgp_block.
When a modal dialog is shown inside Pgp_block that has a small height (it may contain a little of text or just a PGP/Mime attachment) the modal dialog (look at the screenshot) doesn't fit inside the block.
I would recommend increasing pgp_block height or show this modal dialog outside the block (show it on the whole page).

Attachment:
image

### PR DESCRIPTION
**Pull request by limonte**
Fixes #2434

### CODE REVIEW

**Comment by limonte** [comment]
@tomholub sorry to dismiss your review by the tiny naming change :)

**Comment by tomholub** [comment]
I think this one fixes #2214

**Comment by tomholub** [comment]
Here the tests seem to fail for real

**Comment by limonte** [comment]
1 test is failing here, I'll take a look. @tomholub If possible please check what could be the issue with https://github.com/FlowCrypt/flowcrypt-browser/pull/2814#issuecomment-652067301 False negatives are the reason to sometimes ignore checking the build.

**Comment by tomholub** [comment]
> 1 test is failing here, I'll take a look. @tomholub If possible please check what could be the issue with [#2814 (comment)](https://github.com/FlowCrypt/flowcrypt-browser/pull/2814#issuecomment-652067301) False negatives are the reason to sometimes ignore checking the build.

To be honest I'm not sure. Maybe it's related to recent GitHub outages. I wrote Semaphore support to look into it.

**Comment by limonte** [comment]
> > 1 test is failing here, I'll take a look. @tomholub If possible please check what could be the issue with [#2814 (comment)](https://github.com/FlowCrypt/flowcrypt-browser/pull/2814#issuecomment-652067301) False negatives are the reason to sometimes ignore checking the build.
> 
> To be honest I'm not sure. Maybe it's related to recent GitHub outages. I wrote Semaphore support to look into it.

Thank you, I also think it's something on their side and we can't do much aside reporting the issue to Semaphore.

**Pull request merged**
