### PR TITLE
Add upgrade-insecure-requests to CSP [waiting for Tom]

### PR DESCRIPTION
**Pull request by seisvelas**
Last time I made this change I broke the build, but I didn't see those tests break at the time because I'd improperly named the branch. This time I've properly named the branch so I can work on this, properly.

### CODE REVIEW

**Comment by tomholub** [comment]
When this happens, it's because it had too many failures and the tests timed out.

image

You can try to run one particular test locally by adding `.only` to it, then run the enterprise mock version.

**Comment by seisvelas** [comment]
In the tests, I fail by getting this message many times:


```
----- mockBackendData Catch.reportErr -----
name: Errormessage: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForwardurl: chrome-extension://bgniedaillimclcloodjehmoomfikodh/chrome/settings/index.htm?account_email=

trace: 
Error: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForwardat 
Function.Catch.nameAndDetailsAsException (chrome-extension://bgniedaillimclcloodjehmoomfikodh/js/common/platform/catch.js:306:15)
at Function.Catch.report (chrome-extension://bgniedaillimclcloodjehmoomfikodh/js/common/platform/catch.js:144:27)
at Function.Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://bgniedaillimclcloodjehmoomfikodh/js/common/settings.js:326:23)
at async SettingsView.<anonymous> (chrome-extension://bgniedaillimclcloodjehmoomfikodh/chrome/settings/index.js:209:28)
details:[typeof:object:[object Object]] {"acctEmail":"","result":"Error","error":"Wrong oauth state response: Error: Missing oauth state header"}
### Catch.reportErr calling stack ####     
at Function.Catch.formattedStackBlock (chrome-extension://bgniedaillimclcloodjehmoomfikodh/js/common/platform/catch.js:302:44)#     
at Function.Catch.reportErr (chrome-extension://bgniedaillimclcloodjehmoomfikodh/js/common/platform/catch.js:132:26)#     
at Function.Catch.report (chrome-extension://bgniedaillimclcloodjehmoomfikodh/js/common/platform/catch.js:144:11)#     
at Function.Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://bgniedaillimclcloodjehmoomfikodh/js/common/settings.js:326:23)#     
at async SettingsView.<anonymous> (chrome-extension://bgniedaillimclcloodjehmoomfikodh/chrome/settings/index.js:209:28)## 
url: chrome-extension://bgniedaillimclcloodjehmoomfikodh/chrome/settings/index.htm?account_email=
#######################
```

The core problem seems to be `Wrong oauth state response: Error: Missing oauth state header`

I don't really understand what's happening that triggers this, since when I manually try to see this error using `node ./build/test/test/source/mock.js` everything seems fine. I'll continue looking into it.

**Comment by seisvelas** [comment]
For anyone who's following along:

The reason the tests were initially failing is because the upgrade-insecure-requests header caused the browser to upgrade the requests to localhost:8001 (the mock API) to https, which the mock API couldn't handle. I fixed that by changing the mock API to speak HTTPS.

That basically works (I pass lots of tests and when I build and run the extension manually everything is fine), but in the tests I get the error mentioned in the previous comment.

**Comment by seisvelas** [comment]
Happy update: I found a way to make this happen locally. I build and run chrome-consumer-mock. I click Add Account and log in as test-ci-trial. *Then* I click Add Account again and try to log in as flowcrypt-compatibility. A modal pops up saying -

> Failed to connect to Gmail(new). If this happens repeatedly, please write us at human@flowcrypt.com to fix it.
> 
> [Error] Wrong oauth state response: Error: Missing oauth state header

I can check the JS console and see the error:

```
Error: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForward
    at Function.Catch.nameAndDetailsAsException (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:306:15)
    at Function.Catch.report (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:144:27)
    at Function.Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/settings.js:326:23)
    at async SettingsView.<anonymous> (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/chrome/settings/index.js:201:28)


details:
[typeof:object:[object Object]] {"result":"Error","error":"Wrong oauth state response: Error: Missing oauth state header"}

### Catch.reportErr calling stack ###
#     at Function.Catch.formattedStackBlock (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:302:44)
#     at Function.Catch.reportErr (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:132:26)
#     at Function.Catch.report (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:144:11)
#     at Function.Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/settings.js:326:23)
#     at async SettingsView.<anonymous> (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/chrome/settings/index.js:201:28)
# 
# url: chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/chrome/settings/setup.htm~censored:idToken
# 
######################

Catch.onErrorInternalHandler @ catch.js:77
Catch.reportErr @ catch.js:141
Catch.report @ catch.js:144
Settings.newGoogleAcctAuthPromptThenAlertOrForward @ settings.js:326
async function (async)
Settings.newGoogleAcctAuthPromptThenAlertOrForward @ settings.js:307
(anonymous) @ index.js:201
cbWithErrsHandled @ ui.js:75
(anonymous) @ ui.js:111
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
catch.js:81 [failed to log into google in newGoogleAcctAuthPromptThenAlertOrForward]
Error: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForward
    at Function.Catch.nameAndDetailsAsException (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:306:15)
    at Function.Catch.report (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:144:27)
    at Function.Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/settings.js:326:23)
    at async SettingsView.<anonymous> (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/chrome/settings/index.js:201:28)
details:[typeof:object:[object Object]] {"result":"Error","error":"Wrong oauth state response: Error: Missing oauth state header"}
### Catch.reportErr calling stack 
####     at Function.Catch.formattedStackBlock (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:302:44)
#     at Function.Catch.reportErr (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:132:26)
#     at Function.Catch.report (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/platform/catch.js:144:11)
#     at Function.Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/js/common/settings.js:326:23)
#     at async SettingsView.<anonymous> (chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/chrome/settings/index.js:201:28)
# # url: chrome-extension://gogkkjnkpkbkgijedmjhgoacehoccpia/chrome/settings/setup.htm~censored:idToken# ######################
catch.js:112 FlowCrypt ERROR: Please report errors above to human@flowcrypt.com. We fix errors VERY promptly.
```

**Comment by seisvelas** [comment]
The thing is, the tests worked before I changed the API to HTTPS, so the problem must have something to do with that. No idea why, though.

**Comment by tomholub** [comment]
> The thing is, the tests worked before I changed the API to HTTPS, so the problem must have something to do with that. No idea why, though.

I will take some time before I can dedicate time to look into this. I think you are on the right track, though.

**Review by tomholub — APPROVED** [review]

**Pull request merged**
