### PR TITLE
#4630 Show encrypted reply/forward box when user clicks Switch to encrypted reply button

### LINKED ISSUE #4630: Show encrypted reply/forward box when user clicks `Switch to encrypted reply` button.
It's not the worst - at least it still gives the user a chance to choose "reply" or "forward". It could be improved - for example by looking at whether the plain response draft was a rely or forward. But that is getting complicated, maybe leave it for another issue?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4621#issuecomment-1224156309_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR shows encrypted reply/forward box when user clicks Switch to encrypted reply button

close #4630 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
https://github.com/FlowCrypt/flowcrypt-browser/pull/4751 need to be reviewed first. (This PR depends on that PR).
By the way as UI testing is not implemented, please check manually.

**Comment by rrrooommmaaa** [comment]
Can we rename this branch so that it ends with `-live-test` or `-gmail-test`?
Looks like I'm having some problems running the live tests with Puppeteer 19.
Are live tests running smoothly on Sempahore?

**Comment by ioanmo226** [comment]
Well, i can't.
Currently semaphoreci live tests are broken and waiting your changes in https://github.com/FlowCrypt/flowcrypt-browser/pull/4723

**Comment by ioanmo226** [comment]
@rrrooommmaaa  Why did you close this branch?

**Comment by rrrooommmaaa** [comment]
It's done automatically when renaming the branch.
Need to re-create PR on `feature/issue-4630-gmail-test` branch

**Comment by rrrooommmaaa** [comment]
> Currently semaphoreci live tests are broken and waiting your changes in #4723

I assume they got broken when switching to Puppeteer 19.
Puppeteer 18 was ok even without #4723, can we roll back Puppeteer or fix it?

**Comment by ioanmo226** [comment]
No, Live tests have been already broken for several weeks.

**Comment by ioanmo226** [comment]
image

**Comment by rrrooommmaaa** [comment]
Oh, there are 2 failing tests. Perhaps, they are unrelated to Puppeteer. Have you looked into them?

**Comment by ioanmo226** [comment]
Not yet. Will check and fix

**Comment by rrrooommmaaa** [comment]
Looks like this one `mail.google.com - send rich-text encrypted message` has class name changed
image
instead of expected `.nH.if` ?

**Comment by rrrooommmaaa** [comment]
Should be `.nH.hP`?

**Pull request closed without merging**
