### PR TITLE
[WIP] BrowserMsg behavior

### PR DESCRIPTION
**Pull request by limonte**
This PR is not aimed to be merged, its only purpose is to figure out if the `BrowserMsg` behavior is buggy or not.

I stumbled upon this issue where `BrowserMsg` works differently in Chrome and Firefox while working on https://github.com/FlowCrypt/flowcrypt-browser/issues/3629#issuecomment-850676829

### What I'm doing:

1. Sending test action from `webmail.ts`
2. Catching it in `setup-webmail-content-script.ts` along with other listeners
3. Catching it in `compose-render-module.ts`

### Expected behavior (let me know if I'm wrong with my expectations)

The test action is caught both in `setup-webmail-content-script.ts` and `compose-render-module.ts`

### Actual behavior

Behavior is different in Chrome and Firefox, and none of them matches my expectations.

### Actual behavior in Chrome

Test action is caught only in `compose-render-module.ts`:

```
➕ added test_action listener in setup-webmail-content-script.ts, tabId: 17:0
➕ added test_action listener in compose-render-module.ts, tabId: 17:0
↗️ test action sent to 17:0
✔️ caught in compose-render-module.ts
```

### Actual behavior in Firefox

Test action is caught only in `setup-webmail-content-script.ts`:

```
➕ added test_action listener in setup-webmail-content-script.ts, tabId: 1:0
➕ added test_action listener in compose-render-module.ts, tabId: 1:0
↗️ test action sent to 1:0
✔️ caught in setup-webmail-content-script.ts
```

@tomholub questions I need your help with:

- are my expectations correct? 
- is the difference in browsers known? If it is known, where can I read more about it?
- if the difference is unexpected, then we should probably fix it (I depend on this for fixing Gmails shortcuts https://github.com/FlowCrypt/flowcrypt-browser/issues/3629#issuecomment-850676829)

### CODE REVIEW

**Comment by tomholub** [comment]
Sorry I still didn't get to this - when the question is difficult and I don't have enough brain juice left, I have a tendency to delay :-( 

It could be a bug in Firefox (or Chrome). But it could also be that our implementation is not ideal. I'll have to have a look once I can properly focus.

**Comment by tomholub** [comment]
Thank you for the very clear issue demonstration

**Comment by limonte** [comment]
@tomholub let me know if want me to try to fix BrowserMsg implementation. If so, then I'd need your opinion on the expected behavior. My expectations are in the PR description, I'm still not sure if they are correct or not.

**Comment by tomholub** [comment]
Sorry for my continued silence here. @rrrooommmaaa could you take a look later? I didn't have a chance to properly evaluate it yet.

**Comment by rrrooommmaaa** [comment]
First of all, we have separate instances of static handlers mapping `BrowserMsg.HANDLERS_REGISTERED_FRAME`.
I added a feature to chain two handlers and in running on both Firefox and Chrome there are two `adding handler to test_action` console messages.
```
➕ added test_action listener in setup-webmail-content-script.ts, tabId: 5:0 webmail_bundle.js:9844:17
adding handler to test_action webmail_bundle.js:6792:17
```
```
➕ added test_action listener in compose-render-module.ts, tabId: 5:0 compose-render-module.js:60:21
adding handler to test_action browser-msg.js:153:17
```
as stated in https://developer.chrome.com/docs/extensions/mv3/messaging/
in `chrome.runtime.sendMessage` "Note that extensions cannot send messages to content scripts using this method. To send messages to content scripts, use tabs.sendMessage." 
Browsers are indeed behaving differently, mostly because we're trying to use `chrome.runtime.sendMessage` in a way it's not designed to.
In Chrome, I even get 2 messages of 
(2) ✔️ caught in compose-render-module.ts
I can't explain this yet, but if needed we can rewrite this piece of code to use `tabs.sendMessage`, as advised

**Comment by limonte** [comment]
Thank you for investigating this issue @rrrooommmaaa!

> In Chrome, I even get 2 messages of
> (2) ✔️ caught in compose-render-module.ts

Same here.

---

Before trying to fix the issue by replacing `chrome.runtime.sendMessage` with `tabs.sendMessage`, I would like to confirm what is the expected behavior because I'm still not sure about it. I'd expect that the test action can be caught both in `setup-webmail-content-script.ts` and `compose-render-module.ts`.

**Comment by rrrooommmaaa** [comment]
As far as my understanding goes, `webmail_bundle.js` is part of what is called a "content script" (that is a "library" loaded to gmail page), and given that "extensions cannot send messages to content scripts using this method" from the docs, I guess indeterminate behaviour is not a bug. (Perhaps, Firefox has its own interpretation of what to do with trying to send a message to a content script -- the message is visible only within the content script).

**Comment by rrrooommmaaa** [comment]
This was probably fixed with #4264

**Pull request closed without merging**
