### PR TITLE
Issue #1625 Changed version from 1.7.0 to 1.7.13

### PR DESCRIPTION
**Pull request by michael-volynets**
I've checked this method because it uses featherlight:
`Ui.renderOverlayPromptAwaitUserChoice({ finishSetup: {}, later: { color: 'gray' } }, msg);`

Everything looks the same way

#1625

### CODE REVIEW

**Comment by tomholub** [comment]
Look at a possible missing close button when you open any settings sub-page (eg help form)

**Comment by tomholub** [comment]
Or maybe the tag changed so automated tests cannot find the button

**Comment by michael-volynets** [comment]
Yes, There aren't 'data-test' attributes, 
I've added them but I did two commits, I can merge them in one if it's better

**Comment by tomholub** [comment]
No problem, I always squash the PR into one commit when I merge it into master.

**Comment by tomholub** [comment]
I just messed up something on the backend, investigating. It may affect these tests too.

**Comment by michael-volynets** [comment]
I checked the test logs and there are errors only related to 'data-test' attributes.

**Comment by michael-volynets** [comment]
Perhaps would be better to add that attribute in another place?
Because if we update this library the tests will fail again
What do you think?

**Comment by tomholub** [comment]
Sure, it would be better if you can figure out how.

**Comment by michael-volynets** [comment]
I just realized that the page doesn't load at all 

There is the error message you have written in issue #1625.

They haven't fixed the issue yet,
Let's keep the current version of featherlight?

**Comment by tomholub** [comment]
I'll take a look at it later, you can leave this PR as is

**Comment by tomholub** [comment]
Also fixing css to be as before (need larger X button):

From:
image

To:
image

**Pull request merged**
