### PR TITLE
Rework reply buttons

### LINKED ISSUE #3149: rework reply options to be more obvious
I received encrypted email that was

```
from: guy@other.com
to: me@domain.com,george@other.com
cc: andy@other.com,lily@other.com,wes@other.com
```

I click reply all, and I see in secure reply:

```
to: guy@other.com,george@other.com
```
We seem to be ignoring CC emails, which I think is a bug. It's different than what Gmail does.

### PR DESCRIPTION
**Pull request by limonte**
close #3149 

### 2. Reply to all button is shown when `sum(replyParams.to + replyParams.cc + replyParams.bcc) > 1`

---

I also changed the default `font-family` to `-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;`. Here's why: https://github.com/necolas/normalize.css/issues/665

Here's how it looks in Chrome on Windows (default system fonts):

Before:

image

After: 

image

### CODE REVIEW

**Comment by tomholub** [comment]
Looks great!

**Review by tomholub — COMMENTED** [review]
Code looks good, I'd merge this once tests pass :+1:

**Review by tomholub — DISMISSED** [review]

**Review by tomholub — APPROVED** [review]
Thanks!

**Comment by limonte** [comment]
@tomholub I noticed that you deleted this branch after merging. Did you know that GitHub can do that automatically?

https://github.com/FlowCrypt/flowcrypt-browser/settings


image

**Comment by tomholub** [comment]
Thanks for the tip - that was actually an auto-delete I recently set up :+1: they say it's me, but it was done automatically

**Pull request merged**
