### PR TITLE
Remove 5mb limit from license

### PR DESCRIPTION
**Pull request by seisvelas**
Removing 5mb limit everywhere I can find it per https://github.com/FlowCrypt/flowcrypt-backend/issues/304

Let me know if I've missed anywhere on this repo!

### CODE REVIEW

**Comment by seisvelas** [comment]
I'll fix the stylistic issues (unused vars, etc) and update/remove tests, I just made the obvious changes everywhere I saw the limit.

Now I just have to clean up the mess I left :)

**Review by tomholub — DISMISSED** [review]
Looks good. Need to deploy backend changes first

**Comment by tomholub** [comment]
updated backend. Good to merge soon? Just need to rebase to master, should fix the tests.

**Comment by tomholub** [comment]
I'm merging this into #3509

**Comment by tomholub** [comment]
closing in favor of #3509

**Pull request closed without merging**
