### PR TITLE
Add 'Message Not Signed' label to unsigned encrypted messages

### LINKED ISSUE #3366: encrypted + not signed should display to user
If I receive an encrypted message that is signed, I'll see a signature (in green usually).

If I cannot verify the signature / missing public key, it will show in gray.

Currently, if the message is encrypted and not signed, it will show nothing. Instead we should start displaying in gray, where a signature would normally be, "Message Not Signed"

### PR DESCRIPTION
**Pull request by limonte**
This PR adds the 'Message Not Signed' label to unsigned encrypted messages.

image

close #3366

----------------------------------

**Tests** :
- Tests added

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Nice! Let's make it red color :) (I think adding `class=wrong` will use our existing standard red)

**Comment by tomholub** [comment]
Later please request a review from Roman instead of me:

image

**Comment by limonte** [comment]
> Nice! Let's make it red color :) (I think adding `class=wrong` will use our existing standard red)

Done.

image

**Review by rrrooommmaaa — APPROVED** [review]
LGTM!

**Pull request merged**
