### PR TITLE
#5355 Show forwarded message content

### LINKED ISSUE #5355: Forwarded message content should be visible
When user receives encrypted forwarded message, it's content is hidden below `3 dots` button

Screenshot 2023-08-10 at 16 25 56

But when you forward plain message using Gmail, it's content is visible:

Screenshot 2023-08-10 at 16 28 25

We should implement similar behavior:
- move forwarded message above message signature
- add `---------- Forwarded message ---------` in the beginning of forwarded message content
- add this information to the forwarded message:
```
From: Test <test@flowcrypt.com>
Date: Wed, Jul 5, 2023 at 12:15 PM
Subject: Re: Test forward
To: <user1@flowcrypt.com>
Cc: <user-cc@flowcrypt.com>
```

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR updated forward functionality to include forward header information and show forwarded message content

close #5355 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@sosnovsky  Now forward looks like this.
Let me know if you are happy with this.
I'll start to work on fixing tests. Not sure why so many tests fail though
image

**Comment by sosnovsky** [comment]
It looks great 👍

I just noticed bug with forwarded message content - on recipient side forwarded message text is merged into 1 line, so it looks like this:

Screenshot 2023-10-17 at 20 53 10

**Comment by ioanmo226** [comment]
Thanks. Let me check and fix

**Review by sosnovsky — APPROVED** [review]
Well done, looks much better now 👍

**Pull request merged**
