### PR TITLE
#5498 Improve parsing of pgp/mime message with attachment

### LINKED ISSUE #5498: Upgrade puppeteer to v22
After upgrading to puppeteer v21 some tests are failing - https://flowcrypt.semaphoreci.com/jobs/9c365e5a-a511-40c7-b9df-87d1da3b6fd0/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR fixes parsing of large PGP/MIME encrypted messages with attachment, which previously were not detected as encrypted ones.

close #5498

before (original message isn't detected as encrypted and rendered as plain text):

Screenshot 2023-12-14 at 09 54 36

after (encrypted message is parsed and correctly renders decryption error):

Screenshot 2023-12-14 at 09 54 49

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (explain why) - it happens just for some messages, wasn't able to recreate similar pgp/mime message

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
@martgil this one ready for review, thanks!

**Comment by martgil** [comment]
@sosnovsky does the above email from the screenshot available to our `compatibility` email account? Perhaps I can review it and potentially generate a test email for this one?

**Comment by sosnovsky** [comment]
> @sosnovsky does the above email from the screenshot available to our `compatibility` email account? Perhaps I can review it and potentially generate a test email for this one?

Yes, it's in `flowcrypt.compatibility` account - thread `Re: FES message for #5458` from October 16

**Comment by martgil** [comment]
Got it - thank you, Roma.

**Comment by sosnovsky** [comment]
By the way, original message was created using FES 2023-11, the same message from FES 2023-12 doesn't have such issue. Also it happens only in Gmail inbox, while in FlowCrypt Encrypted Inbox message is rendered correctly even without current fix.

**Review by martgil — APPROVED** [review]

**Pull request merged**
