### PR TITLE
Recommend second device

### LINKED ISSUE #1559: recommend a second device to prevent data loss
Keybase did something smart here, we could do the same when both iOS and Android apps are ready:

image

### PR DESCRIPTION
**Pull request by limonte**
Closes #1559 

Questions: 

1. How would you suggest to handle clicking the "Later" link of a banner? It should hide a banner and also remember the user's choice not to see it.
2. Which icon (if any) you prefer?

image

### CODE REVIEW

**Comment by tomholub** [comment]
Where are these icons from? I like them all, and will let you choose.

**Comment by limonte** [comment]
> Where are these icons from? I like them all, and will let you choose.

I made small research of open-source icons with MIT license and found https://github.com/templarian/MaterialDesign/ Icons are from there. The project is well-maintained and community-driven.

I'd go with this one because it shows two devices:

image

**Comment by tomholub** [comment]
> > Where are these icons from? I like them all, and will let you choose.
> 
> I made small research of open-source icons with MIT license and found https://github.com/templarian/MaterialDesign/ Icons are from there. The project is well-maintained and community-driven.
> 
> I'd go with this one because it shows two devices:
> 
> image

Perfect, I would have picked the same. Going forward, feel free to pick on your own.

The license requires attribution as in https://github.com/Templarian/MaterialDesign/blob/master/LICENSE - please find a way to mention it in `CONTRIBUTIONS.md`

> How would you suggest to handle clicking the "Later" link of a banner? It should hide a banner and also remember the user's choice not to see it.

We could save the user choice to local session, as eg `secondDeviceSetupPromptDismissed`. Eventually the browser will clear the session, and then it will reappear.

**Comment by limonte** [comment]
> The license requires attribution as in https://github.com/Templarian/MaterialDesign/blob/master/LICENSE - please find a way to mention it in `CONTRIBUTIONS.md`

Done :+1:

> We could save the user choice to local session, as eg `secondDeviceSetupPromptDismissed`. Eventually the browser will clear the session, and then it will reappear.

Done :+1:

**Comment by limonte** [comment]
TODO:

 - @limonte https://github.com/FlowCrypt/flowcrypt-browser/pull/2476/files#diff-79ae6c03dca9b85adc013c81be41457bR67 after @tomholub approves the outlook of banners
- @tomholub https://github.com/FlowCrypt/flowcrypt-browser/pull/2476/files#diff-635d448465ca9c59ce859a2ac1019265R192

**Comment by tomholub** [comment]
I noticed that "proceed with send permission only" is broken anyway. Let me see if I can fix it.

**Comment by tomholub** [comment]
I will remove option to proceed setup without all permissions. I was broken and nobody told me anyway, meaning it's probably not very common.

For now I'll leave the banners there, for users who have already gone through the setup.

**Pull request merged**
