### PR TITLE
[9h] Issue #984, Decrypt and add attachments from previous message

### PR DESCRIPTION
**Pull request by michael-volynets**
Issue #984,
Time Spent: 5h

Now when we forward a message the attachments will be added to the forwarded message too,
Originally I was thinking to send encrypted attachments without decryption and encryption again but then I realized that we will have a `key mismatch` issue so I had to decrypt and encrypt them with primary user private key.

### CODE REVIEW

**Comment by tomholub** [comment]
Yes, you cannot just pass them along as is, because the recipient may differ. They indeed have to be decrypted and re-encrypted.

**Comment by michael-volynets** [comment]
Great improvement, actually I didn't think about it, Thanks!

**Comment by michael-volynets** [comment]
So, now when replying on some message the attachments won't be decrypted but I think to avoid loading attachments at all we need to change getting message from `raw` format to `full` but to do this we have to change almost whole `getAndDecryptMessage` method so I would recommend to move it to another issue.

**Comment by michael-volynets** [comment]
+30m

**Comment by tomholub** [comment]
It works for detached attachments, but not for pgp/mime type of attachments.

Try this message: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#label/tests%2Fattachment/WhctKHTCKmjFMNVCrvMcxSVtFQHKSBTflcZqSlQqTZSsWjNgQwXQjMNPHblkSqRscsRghmQ

**Comment by tomholub** [comment]
Another issue is that when I click `Forward`, the recipients field should be empty, and in focus. I'll make another issue for this.

**Comment by michael-volynets** [comment]
let me check, Thanks

**Comment by michael-volynets** [comment]
+2h 30m

**Comment by michael-volynets** [comment]
Lookin into tests

**Comment by michael-volynets** [comment]
+ 30m

**Pull request merged**
