### PR TITLE
Run Gmail tests only for master and branches that contain `live-test` or `gmail-test` + re-enable and fix flaky test

### LINKED ISSUE #4020: live test "mail.google.com - secure reply btn, reply draft" fails often
```
  ✖ mail.google.com - secure reply btn, reply draft [ALL RETRIES FAILED for mail.google.com - secure reply btn, reply draft] 10:07
    ℹ (attempt 1 of 3) Retrying: TimeoutError: waiting for selector `[data-test="send-btn-note"]` failed: timeout 20000ms exceeded 10:07
    ℹ (attempt 2 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="input-body"] 10:07
    ℹ (attempt 3 of 3) Failed:   Error: waiting failed: Elements did not appear: [data-test="input-body"] 10:07
          at ControllablePage.ControllableBase.waitAny (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:84:11) 10:07
          at ControllablePage.ControllableBase.waitForContent (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:317:5) 10:07
          at pageHasSecureDraft (/home/semaphore/git/flowcrypt-browser/test/source/tests/gmail.ts:65:9) 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/tests/gmail.ts:273:22 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/test.ts:76:7 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:143:61 10:07
          at BrowserPool.withNewBrowserTimeoutAndRetry (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:143:11) 10:07
          at /home/semaphore/git/flowcrypt-browser/test/source/test.ts:71:5 10:07
          at <async> waitAny (/test/source/browser/controllable.ts:64:19) 10:07
          at <async> waitForContent (/test/source/browser/controllable.ts:316:26) 10:07
          at <async> pageHasSecureDraft (/test/source/tests/gmail.ts:62:31) 10:07
          at <async> <anonymous> (/test/source/tests/gmail.ts:256:101) 10:07
  10:07
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49)
```

### LINKED ISSUE #4022: test "mail.google.com - multiple compose windows, saving/opening compose draft" fails sometimes
https://flowcrypt.semaphoreci.com/jobs/36e1113d-0585-4f5e-9468-a1ee11a3aa62

```
mail.google.com - multiple compose windows, saving/opening compose draft [ALL RETRIES FAILED for mail.google.com - multiple compose windows, saving/opening compose draft] 06:49
    ℹ (attempt 1 of 3) Retrying: Error: Selector @input-body was found but did not match "compose draft" within 20s. Last content: "[ 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n", 06:49
        "\n" 06:49
      ]" 06:49
    ℹ (attempt 2 of 3) Retrying: TimeoutError: waiting for selector `[class^="open_draft_"]` failed: timeout 20000ms exceeded 06:49
    ℹ (attempt 3 of 3) Failed:   TimeoutError: waiting for selector `[class^="open_draft_"]` failed: timeout 20000ms exceeded 06:49
          at new WaitTask (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/src/common/DOMWorld.ts:777:28) 06:49
          at DOMWorld.waitForSelectorInPage (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/src/common/DOMWorld.ts:631:22) 06:49
          at Object.internalHandler.waitFor (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/src/common/QueryHandler.ts:78:19) 06:49
          at DOMWorld.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/src/common/DOMWorld.ts:489:25) 06:49
          at Frame.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/src/common/FrameManager.ts:1163:47) 06:49
          at Page.waitForSelector (/home/semaphore/git/flowcrypt-browser/node_modules/puppeteer/src/common/Page.ts:3035:29) 06:49
          at ControllablePage.ControllableBase.waitAll (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:57:27) 06:49
          at ControllablePage.ControllableBase.waitAndClick (/home/semaphore/git/flowcrypt-browser/test/source/browser/controllable.ts:280:18) 06:49
          at /home/semaphore/git/flowcrypt-browser/test/source/tests/gmail.ts:299:23 06:49
          at /home/semaphore/git/flowcrypt-browser/test/source/test.ts:76:7 06:49
          at <async> waitAll (/test/source/browser/controllable.ts:46:19) 06:49
          at <async> waitAndClick (/test/source/browser/controllable.ts:276:24) 06:49
          at <async> <anonymous> (/test/source/tests/gmail.ts:287:126) 06:49
          at <async> <anonymous> (../test/source/test.ts:71:53) 06:49
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49)
```

### PR DESCRIPTION
**Pull request by limonte**
Because it's not possible to make Gmail tests robust when running them in parallel, this PR changes the SemaphoreCI config so that Gmail tests will run only for:

- `master` branch
- branches that contain `live-test` or `gmail-test` in them

Also, stabilized Gmail tests so all of them now pass without retries:

```
  ✔ mail.google.com/chat (34.6s)
    ℹ run time: 28s
  ✔ mail.google.com - setup prompt notif + hides when close clicked + reappears + setup link opens settings (49.4s)
    ℹ run time: 43s
  ✔ mail.google.com - plain reply to encrypted and signed messages (1m 52.6s)
    ℹ run time: 57s
  ✔ mail.google.com - send rich-text encrypted message (1m 52.7s)
    ℹ run time: 72s
  ✔ mail.google.com - success notif after setup, click hides it, does not re-appear + offers to reauth (2m 9.8s)
    ℹ run time: 123s
  ✔ mail.google.com - rendering attachmnents (2m 59.9s)
    ℹ run time: 61s
  ✔ mail.google.com - pubkey gets rendered with new signed and encrypted Thunderbird signature (3m 0.3s)
    ℹ run time: 61s
  ✔ mail.google.com - msg.asc message content renders (4m 8s)
    ℹ run time: 61s
  ✔ mail.google.com - secure reply btn, reply draft (5m 6.4s)
    ℹ run time: 170s
  ✔ mail.google.com - pubkey file gets rendered (5m 6.9s)
    ℹ run time: 53s
  ✔ mail.google.com - saving and rendering compose drafts when offline (6m 4.9s)
    ℹ run time: 179s
  ✔ mail.google.com - Thunderbird signature [plain] is recognized + correct height (6m 35.3s)
    ℹ run time: 82s
  ✔ mail.google.com - decrypt message in offline mode (7m 3.7s)
    ℹ run time: 52s
  ✔ mail.google.com - setup prompt notification shows up + dismiss hides it + does not reappear if dismissed (7m 20s)
    ℹ run time: 38s
  ✔ mail.google.com - multiple compose windows, saving/opening compose draft (7m 32s)
    ℹ run time: 139s
  ✔ mail.google.com - plain reply draft (8m 22.5s)
    ℹ run time: 55s
  ✔ mail.google.com - Thunderbird signature [html] is recognized (8m 33s)
    ℹ run time: 82s
```

close #4020
close #4022

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by limonte** [comment]
@tomholub I'm afraid I wouldn't be able to make live gmail tests robust when two or more build are happening in parallel in CI. For example, the `saving/opening compose draft` test saves and reads a draft. If this test would be running in two parallel CI builds, the flakiness is inevitable. 

What we need is **one CI build at the time**. In other words no parallel builds at all, neither between PRs nor between the `master` branch and PRs.

Currently, Semaphore CI will only prevent parallelism within the same branch, e.g. when the new commit is pushed to the branch, the previous build on this branch would be stopped. This is due to the `auto_cancel` config: https://github.com/FlowCrypt/flowcrypt-browser/blob/d959ea99f1aeeb146873db5c5fca504cdb4da9ee/.semaphore/semaphore.yml#L8-L10

Unfortunately, I wasn't able to find in semaphoreci docs how to limit the number of parallel workflows to 1, any help would be welcome.

**Comment by tomholub** [comment]
Would you be able to always use a different message/conversation for the test? Create a new one for each test, I suppose, so that they wouldn't conflict?

**Comment by limonte** [comment]
> Would you be able to always use a different message/conversation for the test? Create a new one for each test, I suppose, so that they wouldn't conflict?

Unfortunately, this isn't possible for testing compose drafts.

**Comment by limonte** [comment]
> You could skip live gmail tests for all branches except master.
> 
> We may break them more often, but we'll still notice before we release, 

I was thinking about this option as well, but I decided not to propose it because of these concerns:

1. In case we do so, we would also need a way to create a PR that would run live tests (e.g. there's a change in Gmail test or there's a new gmail test). That's hopefully doable by configuring Semaphoreci to run the `live Gmail tests` job for the `master` branch as well as for branches that contain some trigger word e.g. `run-live-tests`
2. That would be an additional responsibility for a developer to verify that the `master` branch is green 10 min after his PR was merged. I'm personally doing this, but I'm pretty sure it would be a burden for some people. And what would happen for example if two PRs from two different devs merged at the same time and in 10 min master fails? Then it would take additional time to figure out which PR is to blame and who should take care of that.

These details make me feel that the dev workflow would be more complicated than it is now.

**Comment by tomholub** [comment]
I understand these reservations, and agree. For workarounds as you say we can have a trigger word for branches that work on live tests.

For the second concern, we'd have to let go a bit. Devs would just do their work, and most of the time, the tests on master should not break. When they do, it would have to be addressed individually the next day. Not ideal, sure. But it would not actually stop all workflow because feature branches don't run live tests, so having some tests start failing on master would not be a show stopper (unless we need to release).

A compromise would be, if you want to, to split live tests even futher, into two groups. ConcurrentGmailTests and SerialGmailTests. Concurrent would run on every PR like now, and the few that are serial would only run on master and/or trigger word branches.

**Review by tomholub — APPROVED** [review]

**Pull request merged**
