### PR TITLE
Issue #1517, Focus body after sending message to make Gmail shortcuts work

### PR DESCRIPTION
**Pull request by limonte**
@tomholub I accidentally pressed the "Create PR" button instead of creating a draft :man_facepalming: 

I need you help here. This change should fix the issue, but for now it doesn't. It seems that this listener isn't being triggered https://github.com/FlowCrypt/flowcrypt-browser/pull/2084/files#diff-668908dbb47e93967b144b8ef0658932R109 and I can't understand why. Could you give me any hint on this?

### CODE REVIEW

**Comment by tomholub** [comment]
One thing to note is that these BrowserMsg are asynchronous, so it may take a few more event loop cycles for it to actually do something.

Have you confirmed that the body of the handler runs? With a console.log/alert or something?

A side note, you could probably just re-use `focus_frame` since it does the same thing, but maybe have a special keyword like `root` or a null, so that it knows to focus the main frame. Then you don't need to be adding another browser msg type.

**Comment by tomholub** [comment]
A few more hints:
1) this may be the first time you have edited a content script. When you edit content scripts (unlike editing extension frames), you have to actually reload the whole plugin in `chrome://extensions` or in `about:addons`, else the old code will still run (without any handler). Same for background scripts.
2) make sure the handler is called at all with a log/alert
3) make sure the other focus_frame handler is NOT run from elsewhere, overriding your focus
4) eventually make them both a single handler

Let me know if this helps

**Comment by limonte** [comment]
> this may be the first time you have edited a content script. When you edit content scripts (unlike editing extension frames), you have to actually reload the whole plugin in chrome://extensions or in about:addons, else the old code will still run (without any handler). Same for background scripts.

This was helpful, thank you! The PR is ready for review now. I decided to keep the `focus_body` listener because now it's actually different from `focus_frame` and also IMO `focusBody` it's better for code readability than `focusFrame(null)`.

**Comment by tomholub** [comment]
It works!!! :tada:

**Pull request merged**
