### PR TITLE
[2h] Issue 2033 reply all not working

### PR DESCRIPTION
**Pull request by michael-volynets**
Issue #2033,
Time Spent: ~1h

Before merging please merge PR in FlowCrypt/bin and re-run tests

### CODE REVIEW

**Comment by tomholub** [comment]
re-runing

**Comment by michael-volynets** [comment]
The tests failed because of #2034 (I'm working on it now),

we need to merge #2034 first when it's ready and then this issue will pass the tests

**Comment by tomholub** [comment]
Ok so I'm waiting until further updates

**Comment by tomholub** [comment]
Pls have a look at the conflicts

**Pull request merged**
