### PR TITLE
Bump puppeteer to 1.20.0

### PR DESCRIPTION
**Pull request by limonte**
Another try to upgrade to the latest version from v1.

Because for #2051 I'll most probably need `waitForFileChooser` which was introduced in 1.19.0: https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-class-filechooser

### CODE REVIEW

**Comment by limonte** [comment]
Good, only one test is failing, I'll take a look

**Comment by tomholub** [comment]
Doesn't look like puppeteer's fault, maybe a flake, although it did fail reliably.

**Comment by limonte** [comment]
The retrieving message was happening too fast for two `waitForContent`s, after replacing with one `waitForContent` all is well.

**Comment by tomholub** [comment]
Looks good, thanks!

**Pull request merged**
