### PR TITLE
#5144 fix: can't open encryptd draft issue after passphrase expire

### LINKED ISSUE #5144: Can't open encrypted draft for non-encrypted thread
1) open thread with non-encrypted messages
2) click `Secure reply`
3) enter some reply text and save this draft
4) restart browser
5) open this thread
6) instead of draft there is `Waiting for pass phrase to open draft...` label

There should be `Enter passphrase` button below this label, so users will be able to enter passphrase for decrypting draft.

It happens only for cases when passphrase is stored only during current session (for example, for `@flowcrypt.com` users)

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed encrypted draft open issue when passphrase expired

close #5144 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (Testing the process of opening an encrypted draft within a thread cannot be simulated in a mock test and should only be done in live tests. However, it can be challenging to reproduce the behavior of an expired passphrase during live testing. Additionally, testing with drafts within a thread can be unstable since they may be discarded at any time.)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by sosnovsky — COMMENTED** [review]
Looks nice 👍

Can we add check and show it just when there is no other message with `Enter passphrase` block? As currently we have almost identical blocks for encrypted message and draft:

Screenshot 2023-05-09 at 14 18 36

So it should work like this:
- if there is no other message requiring passphrase - show `Enter passphrase` button in draft block
- if there is encrypted message requiring passphrase, then show `Enter passphrase` button in message block, and `Waiting for pass phrase to open draft...` in draft block

**Comment by ioanmo226** [comment]
Upon checking, it seems difficult to determine if there are other PGP messages in the thread. Since both messages and drafts are rendered simultaneously, attempting to check the PGP iframe in the draft render code may return 0 results, even if there are actually PGP messages present.

**Comment by sosnovsky** [comment]
> Upon checking, it seems difficult to determine if there are other PGP messages in the thread. Since both messages and drafts are rendered simultaneously, attempting to check the PGP iframe in the draft render code may return 0 results, even if there are actually PGP messages present.

then let's simplify UI for draft, so it'll be a bit different from message `Enter passphrase` block:

Screenshot 2023-05-09 at 22 40 29

**Review by sosnovsky — APPROVED** [review]
👍

**Pull request merged**
