### PR TITLE
Issue #2292, Created a test

### PR DESCRIPTION
**Pull request by michael-volynets**
Issue #2292,
Time Spent: 40m

I will make a PR with updated `flowcryptcompatibility` mock data to `flowcrypt-bin` repository. When you merge it please re-run tests.
Thanks!

### CODE REVIEW

**Comment by tomholub** [comment]
The test just renders a blank screen on `Page 3 (active) chrome-extension://bgniedaillimclcloodjehmoomfikodh/chrome/elements/compose.htm?acctEmail=flowcrypt.compatibility%40gmail.com&draftId=&threadId=16cfa9001baaac0a&replyMsgId=16cfa9001baaac0a&to=censored%40email.com&cc=&bcc=&from=flowcrypt.compatibility%40gmail.com&subject=Test%20Draft%20Save&frameId=none&tabId=12%3A0&isReplyBox=___cu_true___&skipClickPrompt=___cu_false___&parentTabId=0&disableDraftSaving=___cu_false___&debug=___cu_true___&removeAfterClose=___cu_false___&replyPubkeyMismatch=___cu_false___`, not sure what the problem is

image

**Comment by michael-volynets** [comment]
I just reran the test locally (previously removed `compatibility` account mock data) and it has passed.

**Comment by tomholub** [comment]
It keeps failing on two other draft tests. I suspect the new dataset is missing some drafts.

image

image

Failing on other PRs too.

I'll roll back the mock data. Maybe I have deleted the drafts from compat account? 
I recommend we don't pull drafts when exporting, and hardcode the drafts into the `Data` class. Just strip any sensitive info from them.

**Comment by tomholub** [comment]
After I reverted it, the other PRs indeed started passing again.

**Comment by michael-volynets** [comment]
> I recommend we don't pull drafts when exporting, and hardcode the drafts into the Data class. Just strip any sensitive info from them.

Okay, I will do that for both tests, it will be better and it won't break.
Thanks

**Comment by michael-volynets** [comment]
+1h 20m

**Pull request merged**
