### PR TITLE
Display (some) pgp errors in a separate placeholder

### LINKED ISSUE #4253: sometimes "encrypted" badges are colored red.
To reproduce: pass phrase should not be entered.
Thus, "decrypt error" red badge is displayed.
After entering pass phrase and successful decryption, the badge has now (at least) two classes: "red_label green_label". Red one overrides the green one.
image
Perhaps, we need a separate placeholder for intermediate errors? ("decrypt error" and "parse error") or make sure the whole iframe is reloaded?

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
This PR displays pgp error in a separate badge for easier removal

close #4253

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by rrrooommmaaa** [comment]
do we need a test for the passphrase case?

**Comment by tomholub** [comment]
> do we need a test for the passphrase case?

I'm not too worried about this one. If we ever manage to break it, then we'll write a test for it.

**Review by tomholub — APPROVED** [review]
looks good when separate

**Comment by tomholub** [comment]
@rrrooommmaaa is this ok for a release? I'll be doing on in the next 30 minutes

**Pull request merged**
