### PR TITLE
upgrade version of [check for email] GitHub action to v21

### LINKED ISSUE #4374: inspect [check-for-email] github action
> There were 1 email addresses found in the above comment. Please:
> 
>     1. Click `three dots` -> `edit` to remove the email addresses.
> 
>     2. Click `edited` in the comment header, and click on the previous revision of the comment.
> 
>     3. When viewing the old revision with an email in it, click `options` -> `delete this revision from history`.

@martgil this one seems wrong - since it's on .test domain. Can you take a look?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4372#issuecomment-1091596269_

### PR DESCRIPTION
**Pull request by martgil**
This PR will upgrade the version of [check for email] GitHub action

close #4374 // if this PR closes an issue

issue #0000 // if it doesn't close the issue yet

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Doesn't v20 have some other functionality that it was updated for? You may want to make v21 that incorporates both.

**Comment by martgil** [comment]
@tomholub I just check if there's v21 but there's an error says it doesn't exist:

Screen Shot 2022-04-07 at 8 52 30 PM

maybe I was wrong about downgrading it?

**Comment by tomholub** [comment]
> @tomholub I just check if there's v21 but there's an error says it doesn't exist:
> 
> Screen Shot 2022-04-07 at 8 52 30 PM
> 
> maybe I was wrong about downgrading it?

What I mean is, there was a v20 update which had some purpose but it's buggy. What you'd want to do is fork the code and make v21, which achieves whatever original purpose of v20 without introducing the bug.

**Comment by tomholub** [comment]
I'll fork it and then you can take a look.

**Comment by martgil** [comment]
> > @tomholub I just check if there's v21 but there's an error says it doesn't exist:
> > Screen Shot 2022-04-07 at 8 52 30 PM
> > maybe I was wrong about downgrading it?
> 
> What I mean is, there was a v20 update which had some purpose but it's buggy. What you'd want to do is fork the code and make v21, which achieves whatever original purpose of v20 without introducing the bug.

Thank you. I believe I was able to eliminate the bug within the process of finding exempted emails producing unwanted comments. I just pushed a PR on the forked repo. I'll make a new tag once it was reviewed&merged. thanks again.

**Pull request closed without merging**
