### PR TITLE
Added key usage in KeyUtil.diagnose

### LINKED ISSUE #2789: test key compatibility page
Todo - check if we have a test for this compatibility page

_Originally posted by @tomholub in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDI5Njc5Mzc3/pull_request_reviews/more_threads_

-----------

referring to compatibility.htm accessible under experimental

### LINKED ISSUE #3027: clearly show usage flags in compatibility screen
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJZJSxwPpgDZjjvpMDWzhVRBjw

> I have just received the following after passing my GPG private key:
> 
> This looks like a valid key but it cannot be used for encryption. Please write at human@flowcrypt.com to see why is that.
> 
> Could you kindly help me understand what's the problem?
> Private GPG copied with the following command: $ gpg --armor --export-secret-key [REF]
> GPG generated with the following command: $ gpg --default-new-key-algo rsa4096 --gen-key

I requested the user put the key in compatibility.htm and report the results, which they did:

> (1) Primary keys found: 1  
> (2) ----- Testing key 0 -----  
> (3) PK 0 > Key type: [-] openpgp  
> (4) PK 0 > Is Private?: [-] true  
> (5) PK 0 > User id 0: [-] [REDACED]
> (6) PK 0 > Primary User: [-] [REDACED]
> (7) PK 0 > Fingerprint: [-] [REDACED]
> (8) PK 0 > Subkeys: [-] 0  
> (9) PK 0 > Primary key algo: [-] rsa_encrypt_sign  
> (10) PK 0 > key decrypt: [-] true  
> (11) PK 0 > isFullyDecrypted: [-] false  
> (12) PK 0 > isFullyEncrypted: [-] true  
> (13) PK 0 > Primary key verify: [-] valid  
> (14) PK 0 > Primary key creation?: [-] 1601566359 or 2020-10-01T15:32:39.000Z  
> (15) PK 0 > Primary key expiration?: [-] 1664638359 or 2022-10-01T15:32:39.000Z  
> (16) PK 0 > Encrypt/Decrypt test: Got error performing encryption/decryption test: Error: Error encrypting message: Could not find valid encryption key packet in key 1f8d189539e41ae3:   
> (17) PK 0 > Sign/Verify test: [-] skiped, not fully decrypted  
> (18) PK 0 > expiration: [-] undefined  
> (19) PK 0 > internal dateBeforeExpiration: [-] undefined  
> (20) PK 0 > internal usableButExpired: [-] false  

The user is on Brave

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Shows as per description
```
PK 0 > Usage flags: [-] [sign_data, certify_keys]
```

```
PK 0 > SK 0 > Usage flags: [-] [encrypt_communication, encrypt_storage] 
```
Closes #3027
close #2789

### CODE REVIEW

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
Looks good, I can merge it once it's marked as ready.

**Review by tomholub — COMMENTED** [review]
Looks good but I'm waiting for lawyer's answer regarding re-using LGPL 3.0 code this way.

At the least, all code that was copied and modified should be in a separate file, with a description of the situation on top and a link to https://github.com/openpgpjs/openpgpjs/blob/master/LICENSE

Separately, we should also add a credits page where this should be mentioned. Next to `changelog.txt` we should add `credits.txt` and this should also be linked on the bottom here as a `Credits` link:

image

**Comment by rrrooommmaaa** [comment]
@tomholub If we wish to simplify, we can OR flags from all the signatures. It would give us rough idea in most cases.

**Comment by tomholub** [comment]
No, it looks good as it is. I just need to check the legal side.

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
@rrrooommmaaa sorry for the delay, this is now unblocked. I've tried to merge master to it naively, but it seems the tests need to be adjusted before I can merge the result back to master.

**Review by tomholub — APPROVED** [review]
Thanks!

**Pull request merged**
