### PR TITLE
#5599 Add checks if rich-text option is enabled before removing support

### LINKED ISSUE #5599: Secure reply issues when composing signed message
### Description

When replying to a signed message, pressing enter creates a new line above the current line the user is writing wherein it should create a new line below the current line. Aside from this, pressing backspace does nothing making any typos undeletable.

This only happens on messages composed in a signed message and composing encrypted + signed is not affected.

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRdxBwtHmFKSTKPNLSQSsnqKm
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRfBSrqRfqcSwksGTzqkVdMhQ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxSRMQMmRDKjttmnsQMWRQGDGb

### PR DESCRIPTION
**Pull request by martgil**
This PR adds check ensuring that rich-text is enable before ever removing rich text formatting. This solves the issue of having a prepended newlines when typing, for example, "Hello<kbd>Enter</kbd>World" where it produces 
```
World
Hello
```
in the `contenteditable.div` in the master branch.

To test this manually:

1.) Open Gmail with FlowCrypt browser extension installed and configured.
2.) Send you're self a signed message email.
3.) Reply to your own signed message email.  (*The bug appears at this point on "master" branch but not here.*) 
4.) Type "Hello<kbd>Enter</kbd>World" and it will produce output on `contenteditable.div` correctly with:

```
Hello
World
```
instead of the bugged version:

```
World
Hello
```

close #5599 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (explain why) - It's difficult to test it in automated manners for some reason as I get correct output's when doing testing for both `master` and this branch. So looks like the bug is particularly be reproducible through actual usage. I can share this build to the reporting users for them to double check it -- though it works perfectly when i tested it.

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
Hello @sosnovsky - may I hear your feedback regarding this whenever your are available. Once confirmed that this looks good to you, I'll be sharing a custom build to the reporting users for them to see it working on their side before we can merge this. Thanks!

**Comment by sosnovsky** [comment]
Hi @martgil - I tried to reproduce mentioned bug on `master` build, but everything worked well for me.
Maybe you can share video of this issue by email?
You can also share this build with reporting users, to check if provided fix works for them.

**Comment by martgil** [comment]
Yes, Roma - I just sent a screencast over secure email. Thanks!

**Comment by martgil** [comment]
I will also create a custom build now and share to the reporting users.

**Review by sosnovsky — APPROVED** [review]
I was able to reproduce original issue, and your fix works well 👍

**Pull request merged**
