### PR TITLE
issue #3944 Message from Thunderbird shows as not signed

### LINKED ISSUE #3944: Thunderbird signed + encrypted message - shows "Message Not Signed" in FlowCrypt [waiting for OpenPGP.js upgrade]
**UPDATE** Seems like openpgp.js issue. We will upgrade to v5 in the #3324.

While working on #3941 I sent 3 types of messages to `ci.tests.gmail@flowcrypt.dev`:

- signed html (all good)
- signed text (all good)
- signed + encrypted html (faced issues)

Here's how it looks like in Thunderbird:

CleanShot 2021-08-30 at 18 43 42@2x

And here's how it looks in FlowCrypt:

CleanShot 2021-08-30 at 18 44 22@2x

### PR DESCRIPTION
**Pull request by IvanPizhenko**
This PR fixes "Message Not Signed" for the message sent from the recent Thunderbird version 

close #3944

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by IvanPizhenko** [comment]
@tomholub @rrrooommmaaa @limonte 
I am trying to investigate this issue. I've sent email using Thunderbird to "Flowcrypt Compatibility" (find it [here](https://mail.google.com/mail/u/2/#inbox/WhctKKXGwPwSVpkNdBZKCGfLjctRQSGvxGgqrwCXsjrpRklQxvFsjRmdLDvNmqsXGMzkXSq)) and copied this unit test (originally written by @limonte):
```typescript
    ava.default('decrypt - unsigned encrypted message', testWithBrowser('compatibility', async (t, browser) => {
      const threadId = '17918a9d7ca2fbac';
      const acctEmail = 'flowcrypt.compatibility@gmail.com';
      const inboxPage = await browser.newPage(t, TestUrls.extension(`chrome/settings/inbox/inbox.htm?acctEmail=${acctEmail}&threadId=${threadId}`));
      await inboxPage.waitAll('iframe', { timeout: 2 });
      const urls = await inboxPage.getFramesUrls(['/chrome/elements/pgp_block.htm'], { sleep: 3 });
      expect(urls.length).to.equal(1);
      const url = urls[0].split('/chrome/elements/pgp_block.htm')[1];
      const signature = ['Message Not Signed'];
      await BrowserRecipe.pgpBlockVerifyDecryptedContent(t, browser, { params: url, content: ['This is unsigned, encrypted message'], signature });
    }));
```
just by changing test name and `threadId` to the one manually picked from browser extension, which points to my test email:
```typescript
    ava.default.only('decrypt - signed encrypted message from Thunderbird', testWithBrowser('compatibility', async (t, browser) => {
      const threadId = '17bfe72dc4aab958';
  ...
```
I expected it to work, because for now the message shows up as "unsigned", but when I run locally my new unit test, it fails here:
```typescript
      await inboxPage.waitAll('iframe', { timeout: 2 });
```
with following errors in the console:
```
[decrypt - signed encrypted message from Thunderbird] console-error: Bad Request: 400 when GET-ing https://localhost:8001/gmail/v1/users/me/threads/17bfe72dc4aab958 object: format -> MOCK thread not found for flowcrypt.compatibility@gmail.com: 17bfe72dc4aab958
    at Function.GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google-auth.js:100:50)
    at Function.Google.gmailCall (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.threadGet (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/gmail.js:35:24)
    at async InboxActiveThreadModule.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:28:40)
    at async InboxView.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.js:43:29)
    at async chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/view.js:27:21

url: chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility@gmail.com&threadId=17bfe72dc4aab958


provided ajax call stack:
    at Function.GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google-auth.js:100:50)
    at Function.Google.gmailCall (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.threadGet (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/gmail.js:35:24)
    at async InboxActiveThreadModule.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:28:40)
    at async InboxView.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.js:43:29)
    at async chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/view.js:27:21

url: chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility@gmail.com&threadId=17bfe72dc4aab958


responseText(0, 1000):
{"error":{"message":"MOCK thread not found for flowcrypt.compatibility@gmail.com: 17bfe72dc4aab958"}}

payload(0, 1000):
[typeof:object:[object Object]] {"format":"metadata"}
    at <async> ajax (/extension/js/common/api/shared/api.ts:67:23)
    at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/email-provider/gmail/google-auth.ts:100:53)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:21:28)
    at <async> threadGet (/extension/js/common/api/email-provider/gmail/gmail.ts:42:21)
[decrypt - signed encrypted message from Thunderbird] console-request: 200 OPTIONS https://localhost:8001/api/help/error: ok
[decrypt - signed encrypted message from Thunderbird] console-log: %cFlowCrypt ERROR: Please report errors above to human@flowcrypt.com. We fix errors VERY promptly. font-weight: bold;
[decrypt - signed encrypted message from Thunderbird] console-request: 200 POST https://localhost:8001/api/help/error: ok
  ✖ decrypt - signed encrypted message from Thunderbird [ALL RETRIES FAILED for decrypt - signed encrypted message from Thunderbird]
    ℹ (attempt 1 of 1) Failed:   TimeoutError: waiting for selector `iframe` failed: timeout 2000ms exceeded
          at new WaitTask (/home/ivan/pro/flowcrypt/flowcrypt-browser/node_modules/puppeteer/src/common/DOMWorld.ts:777:28)
          at DOMWorld.waitForSelectorInPage (/home/ivan/pro/flowcrypt/flowcrypt-browser/node_modules/puppeteer/src/common/DOMWorld.ts:631:22)
          at Object.internalHandler.waitFor (/home/ivan/pro/flowcrypt/flowcrypt-browser/node_modules/puppeteer/src/common/QueryHandler.ts:78:19)
          at DOMWorld.waitForSelector (/home/ivan/pro/flowcrypt/flowcrypt-browser/node_modules/puppeteer/src/common/DOMWorld.ts:489:25)
          at Frame.waitForSelector (/home/ivan/pro/flowcrypt/flowcrypt-browser/node_modules/puppeteer/src/common/FrameManager.ts:1163:47)
          at Page.waitForSelector (/home/ivan/pro/flowcrypt/flowcrypt-browser/node_modules/puppeteer/src/common/Page.ts:3035:29)
          at ControllablePage.ControllableBase.waitAll (/home/ivan/pro/flowcrypt/flowcrypt-browser/test/source/browser/controllable.ts:57:27)
          at /home/ivan/pro/flowcrypt/flowcrypt-browser/test/source/tests/decrypt.ts:355:23
          at /home/ivan/pro/flowcrypt/flowcrypt-browser/test/source/test.ts:76:7
          at /home/ivan/pro/flowcrypt/flowcrypt-browser/test/source/browser/browser-pool.ts:143:61
          at <async> waitAll (/test/source/browser/controllable.ts:46:19)
          at <async> <anonymous> (/test/source/tests/decrypt.ts:351:109)
          at <async> <anonymous> (../test/source/test.ts:71:53)
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49)
----- mockBackendData Catch.reportErr -----
name: Error
message: Bad Request: 400 when GET-ing https://localhost:8001/gmail/v1/users/me/threads/17bfe72dc4aab958 object: format -> MOCK thread not found for flowcrypt.compatibility@gmail.com: 17bfe72dc4aab958
url: chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.htm?acctEmail=flowcr
trace:     at Function.GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google-auth.js:100:50)
    at Function.Google.gmailCall (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.threadGet (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/gmail.js:35:24)
    at async InboxActiveThreadModule.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:28:40)
    at async InboxView.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.js:43:29)
    at async chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/view.js:27:21

url: chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility@gmail.com&threadId=17bfe72dc4aab958


provided ajax call stack:
    at Function.GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google-auth.js:100:50)
    at Function.Google.gmailCall (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/google.js:36:33)
    at async Gmail.threadGet (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/api/email-provider/gmail/gmail.js:35:24)
    at async InboxActiveThreadModule.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:28:40)
    at async InboxView.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.js:43:29)
    at async chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/view.js:27:21

url: chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility@gmail.com&threadId=17bfe72dc4aab958


responseText(0, 1000):
{"error":{"message":"MOCK thread not found for flowcrypt.compatibility@gmail.com: 17bfe72dc4aab958"}}

payload(0, 1000):
[typeof:object:[object Object]] {"format":"metadata"}
    at <async> ajax (/extension/js/common/api/shared/api.ts:67:23)
    at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/email-provider/gmail/google-auth.ts:100:53)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:21:28)
    at <async> threadGet (/extension/js/common/api/email-provider/gmail/gmail.ts:42:21)

### Catch.reportErr calling stack ###
#     at Function.Catch.formatExceptionForReport (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/platform/catch.js:262:90)
#     at Function.Catch.onErrorInternalHandler (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/platform/catch.js:76:29)
#     at Function.Catch.reportErr (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/platform/catch.js:92:18)
#     at InboxActiveThreadModule.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:63:31)
#     at async InboxView.render (chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.js:43:29)
#     at async chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/js/common/view.js:27:21
# 
# url: chrome-extension://mjjicbbflajnkdajeonfeladadbllpgf/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility@gmail.com&threadId=17bfe72dc4aab958
# 
######################
```
On the other hand, original test works good, if I run it locally.
What am I doing wrong?

**Comment by IvanPizhenko** [comment]
@tomholub Btw, "Flowcrypt Compatibility" gets lots of subscription messages from "Kraken" (as I understand cryptocurrency market) which, generally, floods inbox. Is it intentional? If so, maybe it is better to setup a filter and move all these messages to a dedicated folder?

**Comment by limonte** [comment]
@IvanPizhenko follow this instruction for mocking messages: https://github.com/FlowCrypt/flowcrypt-browser/blob/master/test/source/mock/google/google-data.ts#L101

**Comment by limonte** [comment]
@IvanPizhenko just in case, I've sent you instructions for logging into flowcrypt.compatibility@gmail.com

**Comment by IvanPizhenko** [comment]
@limonte Thank you, I'll try that.

**Comment by IvanPizhenko** [comment]
@limonte Thank you! After properly exporting and adding message to the mock - it works.

**Comment by IvanPizhenko** [comment]
```json
>>>> uncheckedUrlParams: {
"acctEmail":"flowcrypt.compatibility@gmail.com",
"frameId":"frame_lFetgNCmRM",
"message":".... PGP MESSAGE ...", "parentTabId":"13:0",
"msgId":"17bfe72dc4aab958",
"isOutgoing":false,
"senderEmail":"sender@domain.com"
}
```

**Comment by IvanPizhenko** [comment]
Finally,
```typescript
  private static cryptoMsgGetSignedBy = async (msg: OpenpgpMsgOrCleartext, keys: SortedKeysForDecrypt) => {
    keys.signedBy = Value.arr.unique(msg.getSigningKeyIds ? msg.getSigningKeyIds().map(kid => OpenPGPKey.bytesToLongid(kid.bytes)) : []);
...
```

**Comment by IvanPizhenko** [comment]
@limonte @rrrooommmaaa I can't understand how it works.

I've found this and added some log:
```typescript
private decryptAndRender = async .... {
      console.log(">>>> PATH #1: before");
      const kisWithPp = await KeyStore.getAllWithOptionalPassPhrase(this.view.acctEmail);
      const result = await BrowserMsg.send.bg.await.pgpMsgDecrypt({ kisWithPp, encryptedData });
      console.log(">>>> PATH #1: after: " + JSON.stringify(result));
...
```
I can see these two log outputs in the browser console.
Then I've found:
```typescript
public static send = {
...
bg: {
....
await: {
....
        pgpMsgDecrypt: (bm: Bm.PgpMsgDecrypt) => BrowserMsg.sendAwait(undefined, 'pgpMsgDecrypt', bm, true) as Promise<Bm.Res.PgpMsgDecrypt>,
.... 
```
and then 
```typescript
    BrowserMsg.bgAddListener('pgpMsgDecrypt', MsgUtil.decryptMessage);
``` 
So I assume when `await BrowserMsg.send.bg.await.pgpMsgDecrypt(...)` is called, it finally calls `MsgUtil.decryptMessage()`.
But when I add some log into it:
```typescript
  public static decryptMessage: PgpMsgMethod.Decrypt = async ({ kisWithPp, encryptedData, msgPwd }) => {
    console.log(">>>> PATH #4");
```
I can't see this in the browser console, like it is not called, but this can't be, because I get the result printed by `console.log(">>>> PATH #1: after: " + JSON.stringify(result));`.
image


How can I get this message (i.e. `console.log(">>>> PATH #4")`) into browser log?

**Comment by limonte** [comment]
@IvanPizhenko 

I guess you want to inspect the background page. 

1. Go to chrome://extensions/
2. Click this link CleanShot 2021-10-05 at 01 53 17@2x

**Comment by IvanPizhenko** [comment]
@limonte Thank you, I will try this.

**Comment by IvanPizhenko** [comment]
From the following debug code:
```typescript
    console.log(">>>> cryptoMsgGetSignedBy: entered");
    console.log(">>>> cryptoMsgGetSignedBy: Message: " + JSON.stringify(msg));
    console.log(">>>> cryptoMsgGetSignedBy: Keys: " + JSON.stringify(keys));
    if (msg.getSigningKeyIds) {
      console.log(">>>> cryptoMsgGetSignedBy: signing key Ids: "
        + JSON.stringify(msg.getSigningKeyIds()));
    } else {
      console.log(">>>> cryptoMsgGetSignedBy: NO signing key Ids");
    }
    keys.signedBy = Value.arr.unique(msg.getSigningKeyIds ? msg.getSigningKeyIds().map(kid => OpenPGPKey.bytesToLongid(kid.bytes)) : []);
    console.log(">>>> cryptoMsgGetSignedBy: Keys.signedBy: " + JSON.stringify(keys.signedBy));
```
I am getting following output:
```
```

**Pull request closed without merging**
