### PR TITLE
Remove customized coloring from console.log and use console.error instead

### PR DESCRIPTION
**Pull request by seisvelas**
Instead of using `console.log` with custom coloring to make the text red, we can use `console.error`. Simpler *and* better!

close https://github.com/FlowCrypt/flowcrypt-browser/issues/3798

----------------------------------

**Tests** _(delete all except exactly one)_:
- Not worth testing

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by seisvelas** [comment]
This will probably fail tests because of the Gmail live tests - once tests finish we have to be super mindful to check that it's actually passing everything else!

**Comment by seisvelas** [comment]
Failing other tests, but I think those also might be broken? Perhaps it's the tests broken by https://github.com/FlowCrypt/flowcrypt-browser/pull/3797 (since that appears to have broken some tests)

I should mark this ready for review once tests are figured out.

**Comment by tomholub** [comment]
@seisvelas master is now ok with tests

**Review by tomholub — APPROVED** [review]
Thanks!

**Pull request merged**
