### PR TITLE
#5839 Fix parsing noname attachment with "message/global" content type

### LINKED ISSUE #5839: Incorrect rendering of "Delivery Status Notification" email messages
Customer reported an issue with `Delivery Status Notification` messages received from Google - FlowCrypt marks them as encrypted and tries to decrypt, causing `Problem extracting armoted message` error.

I checked message structure and seems like this issue is caused by `noname` attachment with `message/global` content type.
Need to handle this case and don't try to decrypt plain message.

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR fixes incorrect parsing of `noname` attachments with `message/global` content type in plain messages.

close #5839

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
Hi @martgil, this PR is ready for review, thanks!

**Comment by martgil** [comment]
Looks good to me – I just noticed one minor thing that could be improved, but it’s definitely not an issue.

**Comment by sosnovsky** [comment]
> Looks good to me – I just noticed one minor thing that could be improved, but it’s definitely not an issue.

Hi @martgil, didn't find this minor thing, can you please describe what can be improved, thanks!

**Comment by sosnovsky** [comment]
> Looks good to me – I just noticed one minor thing that could be improved, but it’s definitely not an issue.

Hi @martgil, can you please describe mentioned improvement, thanks!

**Comment by martgil** [comment]
> Hi @martgil, can you please describe mentioned improvement, thanks!

Thanks @sosnovsky, I'm referring to this one: https://github.com/FlowCrypt/flowcrypt-browser/pull/5844/files#diff-fb2223e49c2a9c6a1085bdbe7eb8e17e3ee803132833d5e90d49faf5a3e8d2faR232-R237

I feel like this function should be renamed to `shouldBeHidden()`, in case of the following test: 

```javascript
if (renderStatus === 'hidden' || a.isHidden()) {
        nRenderedAttachments--;
      }
```
since there's an action that depends on it that requires reduction for attachment that is supposed to be hidden. The function `isHidden()` sounds like a test for attachment that is hidden or not. Not a big deal though.

**Comment by sosnovsky** [comment]
Agree on this, `shouldBeHidden` better describes original property, thanks for noticing!
I renamed it, please re-check

**Review by martgil — APPROVED** [review]
all good now, thank you!

**Pull request merged**
