### PR TITLE
Fixes corrupted filename error

### LINKED ISSUE #3352: filename corrupted causing problems opening
If you encrypt a PDF file with name `XX J 1 IT E (P 4) p_c.pdf` then the encrypted file will have name such as `XX J 1 IT E (P%20` - notice incomplete name, and more importantly no `.pdf.pgp` at the end. This makes the receiving side not recognize it's an encrypted file, and when they download it, it appears corrupted (but it's in fact a normal encrypted file, just badly named).

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
close #3352

### CODE REVIEW

**Review by tomholub — COMMENTED** [review]
Since the test passes, this sounds like the problem may be elsewhere

**Comment by rrrooommmaaa** [comment]
> Since the test passes, this sounds like the problem may be elsewhere

Yes, the problem is related to https://tools.ietf.org/html/rfc2231 
`3.  Parameter Value Continuations`
Ours:
```
Content-Disposition: attachment;
 filename*0*=utf-8''XX%20J%201%20IT%20E%20(P%204)%20p_c.pdf.pg;
 filename*1=p
 ```
 In the RFC example, there is no asterisk after `*0`
 ```
         Content-Type: message/external-body; access-type=URL;
         URL*0="ftp://";
         URL*1="cs.utk.edu/pub/moore/bulk-mailer/bulk-mailer.tar"
         ```

**Comment by tomholub** [comment]
Interesting - thanks for looking into this. Sounds like a fix that needs to land on the emailjs-mime-builder? We use an old version, and have been making fixes in the file directly. I guess that's what would happen here too - as long as we test it properly in our own use of it. Then in the future, we'll starting working on moving to latest emailjs and pushing our fixes upstream.

**Comment by tomholub** [comment]
We may even end up maintaining the library, I talked to the previous maintainer who doesn't have time for it anymore.

**Comment by rrrooommmaaa** [comment]
> Interesting - thanks for looking into this. Sounds like a fix that needs to land on the emailjs-mime-builder? We use an old version, and have been making fixes in the file directly. I guess that's what would happen here too - as long as we test it properly in our own use of it. Then in the future, we'll starting working on moving to latest emailjs and pushing our fixes upstream.

Actually, there is a combination of 'continuation` and `encoding`. Have to find out whether we encode incorrectly or whether gmail parses incorrectly
```
   Content-Type: application/x-stuff
    title*0*=us-ascii'en'This%20is%20even%20more%20
    title*1*=%2A%2A%2Afun%2A%2A%2A%20
    title*2="isn't it!"
    ```

**Comment by rrrooommmaaa** [comment]
It turned out by way of experimentation that `gmail` parses this particular filename in continuation/encoded values correctly if URIEncode brackets `()` as `%28` and `%29`.
I'll test other characters tomorrow, or we can simply URIEncode all characters as other clients do:
```
 filename*0*=UTF-8''%D0%BC%D0%B0%D0%B2%D1%8B%D0%BF%D0%B2%20%67%64%73%64%73;
 filename*1*=%20%75%65%79%72%65%74%72%37%65%20%D0%B0%D0%B2%D1%8B%D0%B2;
 filename*2*=%D1%8B%D0%B2%20%D0%BA%D1%83%D0%BA%D1%83%D0%BA%D1%83%36%34%35;
 filename*3*=%20%33%34%33%34%D0%BE%D0%BF%D1%80%D0%B0%D0%B0%D0%BF%D1%80;
 filename*4*=%D0%B2%20%D0%BC%D1%81%D0%BC%D0%B2%20%D1%83%D0%B0%D1%83%D0%B0;
 filename*5*=%D0%BA%D0%B5%D1%83%D0%B5%D0%BF%D0%B0%20%D0%BF%D0%B0%D0%BF;
 filename*6*=%D0%B2%D0%B0%D0%BF%D0%BA%D0%BF%D0%BB%D1%81%D0%B2%D1%8B%D0%B0;
 filename*7*=%D1%8B%D0%B0%20%D0%B0%D0%BF%D0%B2%D0%B0%D1%83%D0%B2%D0%BF;
 filename*8*=%D0%B0%D0%BF%20%D0%BA%D1%83%D0%B5%D1%83%D0%BA%D0%B5%20%D1%89;
 filename*9*=%D0%BD%D0%B5%D0%BD%D0%BA%D0%BD%D1%88%D0%BA%D0%BC%D0%B8%D1%82;
 filename*10*=%D0%BC%D0%B2%D0%B0%20%20%D0%B8%D0%BF%D0%B0%D0%BF%D0%B0;
 filename*11*=%D0%BF%D0%BF%D0%B8%D0%BC%D1%80%D0%B2%D0%B0%D0%B2%D0%BC;
 filename*12*=%D0%B8%D0%B8%D1%80%D0%B0%D0%B8%D1%82%20%D1%8C%D0%B8%D1%82;
 filename*13*=%D0%BF%D0%B0%D1%80%D0%B8%D0%B0%D0%BF%D1%80%D0%BA%D0%B5;
 filename*14*=%D0%BA%20%31%77%65%65%77%65%65%65%65%65%65%2E%70%64%66
 ```

**Review by tomholub — APPROVED** [review]
Thank you. Since the test was initially already passing before fix, it seems we are not really testing it completely?

**Pull request merged**
