### PR TITLE
add additional check for third case of gmail UI change

### PR DESCRIPTION
**Pull request by martgil**
This PR will add an additional condition check for the third case where Gmail UI change occurs (with sticky sidebar)

close https://github.com/FlowCrypt/flowcrypt-browser/issues/4328

issue #0000 // if it doesn't close the issue yet

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests will be added later (issue #...)
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
please share screenshots:
1) the new design
2) old design collapsed
3) old design extended

**Comment by martgil** [comment]
1. new design:
Screen Shot 2022-03-08 at 9 47 19 PM
2. old design collapsed:
Screen Shot 2022-03-08 at 9 48 06 PM
3. old design extended:
Screen Shot 2022-03-08 at 9 48 28 PM

Thank you, sir!

**Comment by tomholub** [comment]
on my end, this is without changes:

image

image

try another account

**Comment by tomholub** [comment]
tested on firefox

**Comment by martgil** [comment]
sir @tomholub, it should be fixed on firefox as well. 

Could you please try to refresh the addon after `npm run build` by going to `about:debugging#/runtime/this-firefox` or re-loading/re-import the addon to the browser?

Screen Shot 2022-03-09 at 8 38 55 AM

https://user-images.githubusercontent.com/46025304/157350360-7a4db12d-9e61-48c3-8f07-4c1359d5365b.mov

**Comment by tomholub** [comment]
I'm using `npm run-script run_firefox` which always builds and runs the latest code.

**Comment by martgil** [comment]
@tomholub I understand you but most of the time I need to reload the extension for some reason for the recent npm run build and other changes to take effect. Please try the following and see if it works, thanks!:

https://user-images.githubusercontent.com/46025304/157633519-3b5e4681-3477-42b9-9a47-cc33c2e8b629.mov

**Comment by rrrooommmaaa** [comment]
It is indeed updated on both Chrome and Firefox, but I suggest to shift the flowcrypt image to the left for a couple of pixels
image

**Comment by martgil** [comment]
> It is indeed updated on both Chrome and Firefox, but I suggest to shift the flowcrypt image to the left for a couple of pixels 

thank you, sir! I've tried to adjust it by 2 more pixels.

**Comment by tomholub** [comment]
@martgil also, remove the extra "secure compose" text underneath it in the new view

**Review by rrrooommmaaa — APPROVED** [review]

**Pull request merged**
