### PR TITLE
[4h] Issue #2189, fixed bug when footer doubled

### PR DESCRIPTION
**Pull request by michael-volynets**
Issue #2189,
Time Spent: 3h

I also fixed an issue when `TripleDots` button was shown on the reply box with a draft and the button was also rendered (but actually it shouldn't have been rendered), and when you click on it nothing happens.

I haven't found the issue related to this `Tripedots` button bug on Github (it might not be reported).

### CODE REVIEW

**Comment by michael-volynets** [comment]
Yes, I also was thinking like you and actually my first implementation was kind of you wrote in your comment.
But I checked issue #2189 and @limonte described that the expected result is:
```
The message is empty, the signature is hidden in the footer (three dots)
```
And I also think that it's better from the UI side so I implemented it.

But both ways are acceptable so if you want I can remove it and it will make code simpler :)

**Comment by tomholub** [comment]
Sorry, I'm a bit confused now. Did the simpler fix not achieve that? I thought that it was already saving draft including the footer. That means simply not adding another footer when it was loaded for the draft should achieve this result:

> The message is empty, the signature is hidden in the footer (three dots)

Because it was already saved as part of the draft. If I'm wrong, please let me know.

**Comment by michael-volynets** [comment]
Yes, there is a little oversight of what you are saying.
When we save draft we save the footer as well.
So when we do steps that described in the issue the result will be a draft with a recipient and with the message body containing your footer. I mean when we load draft we don't append the footer. The code you listed:
```TS
if(footer && !this.composer.draft.msgWasLoadedFromDraft) {
      this.footerHTML = this.createFooterHTML(footer);
      safePreviousMsg  += this.footerHTML;
}
```
Adds your footer to the expanding part of the message (not to the message body).
So we anyway have to remove footer from the message body and add it to the expanding part.

Your code says that we don't need to show `threedots` button because we already got the footer in the draft message body.

**Comment by michael-volynets** [comment]
+20m

**Pull request merged**
