### PR TITLE
Move pgpHashChallengeAnswer from background script

### PR DESCRIPTION
**Pull request by limonte**
Part of #2158

### CODE REVIEW

**Comment by limonte** [comment]
@tomholub I'm on `master` branch, `npm build` is executed, the extension reloaded (`chrome://extensions`) and getting:

image

for the `[flowcrypt] hosted password encrypted files` test case.

In console I'm seeing

> Access to XMLHttpRequest at 'https://s3-us-west-2.amazonaws.com/cryptup/message/ec8d80cfb9415725cde43feb3c1249a500a6dcf8.asc' from origin 'chrome-extension://dfbpklhlbpikpllkojnfhdhgbomoponf' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is it related to https://github.com/FlowCrypt/flowcrypt-browser/issues/2532 ?

**Comment by tomholub** [comment]
Ever since we dropped `*://*/*` permission, it wants me to add every chrome extension id to CORS on AWS.

The issue is, on every dev machine the extension id will be different.

I'll go ahead and add `chrome-extension://dfbpklhlbpikpllkojnfhdhgbomoponf`. Eventually though, I may remove these tests.

**Comment by tomholub** [comment]
updated

**Comment by limonte** [comment]
> Just realized, all of these listeners should also be in `extension/chrome/settings/inbox` (the "Encrypted Inbox" page), since that one also hosts pgp frames.

Missed that, thank you! Done.

**Pull request merged**
