### PR TITLE
#5569 Add compliance with Trusted Types

### LINKED ISSUE #5569: Check compliance with Trusted Types
Google announced that they extend Trusted Types to Gmail in mid-February - https://workspaceupdates.googleblog.com/2024/01/extending-trusted-types-to-gmail.html:

> This new enforcement mode will require third-party extensions to use [typed objects instead of strings](https://web.dev/trusted-types/#fix-the-violations) when assigning values to DOM APIs. Once Trusted Types are fully enforced, the Trusted Types directive will be present in the Content Security Policy (CSP) header: 
> Content-Security-Policy: require-trusted-types-for 'script';report-uri https://mail.google.com/mail/cspreport

We already use `DOMPurify` library for DOM manipulations, but need to re-check if extension is fully complaint with Trusted Types.

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR adds Trusted Types policy for compatibility with upcoming Gmail policy update

close #5569

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
@martgil this PR is ready for review, thanks!

**Comment by sosnovsky** [comment]
> I think it is also a good idea to update some of the few options for the DOMPurify configuration option to return trusted type by adding the `RETURN_TRUSTED_TYPE` property set to true when `DOMPurify.sanitize()` is used:

Nice suggestion, I'll check this property and also standard dompurify types from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dompurify as we currently use outdated types for v2.

**Comment by sosnovsky** [comment]
@martgil I tried to add `RETURN_TRUSTED_TYPE` property to DOMPurify, but it'll require a lot of changes in our code - at least all usages of `Xss.htmlSanitize`, as currently it returns `string`, but with Trusted Types it's return type will be `string | TrustedHTML`. And also adding `@types/trusted-types` leads to build error, will need investigation too.

So let's plan this change to the next milestone (I created separate issue for it - https://github.com/FlowCrypt/flowcrypt-browser/issues/5576), as we need to finish current release in the beginning of February, before Gmail policy update.
In this PR I've also updated `purify.d.ts` to the latest version from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dompurify

**Comment by martgil** [comment]
> @martgil I tried to add `RETURN_TRUSTED_TYPE` property to DOMPurify, but it'll require a lot of changes in our code - at least all usages of `Xss.htmlSanitize`, as currently it returns `string`, but with Trusted Types it's return type will be `string | TrustedHTML`. And also adding `@types/trusted-types` leads to build error, will need investigation too.

I understood completely. This PR also looks good. thanks!

> So let's plan this change to the next milestone (I created separate issue for it - #5576), as we need to finish current release in the beginning of February, before Gmail policy update. In this PR I've also updated `purify.d.ts` to the latest version from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dompurify

Okay, thanks! I'll assigned it to myself to work on it.

**Review by martgil — APPROVED** [review]
LGTM! thank you.

**Pull request merged**
