### PR TITLE
Change the reply box label from 'Encrypted' to 'Secure'

### LINKED ISSUE #2979: when replying to signed message, the reply box wording is mismatched
Before activating compose box it says "Encrypted" 
image

But once clicking, it is actually signed:
image

We should change the wording of the "Encrypted" maybe to simply "Secure"

### PR DESCRIPTION
**Pull request by limonte**
Fixes #2979

### CODE REVIEW

**Comment by limonte** [comment]
@tomholub couldf you help me to understand what's failing in this PR? The output in semaphoreci is really heavy for some reason and takes forever to load. I opened the raw output, but it wasn't helpful also.

**Comment by tomholub** [comment]
Yeah the semaphore ui has regressed lately being super slow. Let me see.

**Comment by limonte** [comment]
The `master` branch is failing as well, so I assume the issue isn't in this PR

**Comment by tomholub** [comment]
Yup I messed something up on our backend, glad you discovered it. Redeploying..

**Review by tomholub — APPROVED** [review]

**Pull request merged**
