### PR TITLE
Fix pretag pasting

### LINKED ISSUE #2860: wrong newlines when pasting a public key
1) make sure to choose "plain text" type of message using the compose button chevron (this should be the default anyway)
2) copy public key from https://flowcrypt.com/pub/human@flowcrypt.com?show=pubkey
3) paste it into secure compose

result:

image

expected result:

image

I don't know where the problem happens, whether at time of copying or pasting.

### PR DESCRIPTION
**Pull request by nomad-dad**
This PR preserves newlines inside of `pre`s by replacing them with `br`'s.

I marked this difficult to test but in fact, it should be possible using a browser testing library (which you already use) to simulate this. Let me know if you'd like a test with this.

close #2860 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (explain why)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
I approved the tests, but they don't seem to be keen on running (external contribution).

Maybe you can do the same PR but make it come from a branch on this repo directly? I've added you at https://github.com/FlowCrypt/flowcrypt-browser/invitations to be able to do that.

**Comment by tomholub** [comment]
Meanwhile @rrrooommmaaa how does this look?

**Comment by tomholub** [comment]
Meanwhile @sosnovsky how does this look?

**Review by sosnovsky — COMMENTED** [review]
Looks good, but for better readability I would move it to separate method `replaceNewLinesWithBrInPreTags`:

**Comment by tomholub** [comment]
Unfortunately I haven't heard from the author since. I'll just merge it as is.

**Review by tomholub — APPROVED** [review]

**Pull request merged**
