### PR TITLE
Issue #2062, Remove .blur().focus() trick and run parseRenderRecipients() directly

### LINKED ISSUE #2062: new message (not reply) - auto-focus recipients

### PR DESCRIPTION
**Pull request by limonte**
Closes #2062

### CODE REVIEW

**Comment by tomholub** [comment]
I'd imagine, after this fix, you may be able to remove the setTimeout (setHandledTimeout) from earlier and just do a direct focus?

**Comment by limonte** [comment]
> I'd imagine, after this fix, you may be able to remove the setTimeout (setHandledTimeout) from earlier and just do a direct focus?

Good point. Let me check that :+1:

**Comment by tomholub** [comment]
Sorry I meant this:
image

**Comment by limonte** [comment]
@tomholub what the internal agreement on the CR process? I would like to save your time sometimes and not perform review until I'm done with a PR (tests, coding style).

I was thinking that the asignment you as reviewer will mean "hey, this PR is ready, PTAL", but you're taking a look before that. Should I go with drafts in cases I want to polish a contribution before asking you to review it?

**Comment by tomholub** [comment]
Aaah. When I see a PR open, unless it's a draft, I imagine that it's ready (and that you have just forgot to mark me as a reviewer).

Maybe the PR drafts would be best, then I know it's WIP.

**Comment by tomholub** [comment]
Maybe I'm just too excited to be making some progress, so I start wanting to review and merge it from under your feet :laughing: ... drafts will tone down that urge.

**Comment by tomholub** [comment]
But now I see there was no review requested on this one. Let me know when it's cool to merge.

**Comment by limonte** [comment]
> But now I see there was no review requested on this one. Let me know when it's cool to merge.

Hold on, there's one more detail.

**Comment by limonte** [comment]
Alright, now it's ready for review. Tested manually in Firefox in Chrome for both Compose and Reply cases.

**Pull request merged**
