### PR TITLE
Remove deprecated code from pulling public keys from EKM

### LINKED ISSUE #3841: retire pulling public keys keys from EKM
Since we already pull public keys from WKD which is synced with EKM, no need to have a separate endpoint for this.

That means this would simply get removed:

```ts
    if (this.keyManager) {
      const res = await this.keyManager.lookupPublicKey(email);
      if (res.publicKeys.length) {
        return { pubkeys: res.publicKeys.map(x => x.publicKey) };
      }
    }
```

Similarly remove `getKeyManagerUrlForPublicKeys` and everything related to `NO_KEY_MANAGER_PUB_LOOKUP` and adjust tests.

This way, the extension will be more consistent with what mobile apps do, also.

### PR DESCRIPTION
**Pull request by martgil**
This PR will remove deprecated code from pulling public keys from EKM. 

close #3841 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests removed

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
@martgil do you have access to these? https://flowcrypt.semaphoreci.com/jobs/9e7932f1-d6a6-4eb7-89a6-c33103545121

**Comment by martgil** [comment]
I think I don't have permission to check the ci test output.

**Comment by martgil** [comment]
Everything seems to work at least for me after the removal of `NO_KEY_MANAGER_PUB_LOOKUP` related functions. I just removed those functions that are only connected with the request above with my understanding. Please let me know if I did something wrong so I can revert the changes. Thanks!

**Comment by tomholub** [comment]
Have a look at the failing tests above - there is one more test that relies on this functionality which stopped working and should also be removed.

**Review by tomholub — DISMISSED** [review]
Other than further updating the tests, the code changes are correct. Thank you

**Review by tomholub — APPROVED** [review]

**Pull request merged**
