### PR TITLE
#5740 Re-arrange processing of newlines in quoted email

### LINKED ISSUE #5740: Pressing "Enter" twice in beginning/endings of quoted text required before a newline actually rendered
Description:

It was reported to us that it requires them to press the "Enter" on their keyboard twice before a newline to render. Upon further investigation, the issue exists when interacting onto the beginning or endings of the quoted text. To be specific, its on the the line where the "On <date>, <email> wrote:" starts or at the last occuring line of the quoted text "> some quoted text...".

Steps to reproduce:

1. Open Gmail with FlowCrypt browser extension set up.
2. Open any FlowCrypt-renderable emails (encrypted+signed or signed) in your inbox.
3. Click on "Secure Reply".
4. Click onto the "..." icon button on the bottom part of the Secure reply box to see the quoted email text.
5. On the section "On <date>, <email> wrote:" or at the last occuring line of the quoted text "> some quoted text...", try to press <kbd>Enter</kbd> and you'll not be getting an expected newline. It will require you to press <kbd>Enter</kbd> twice for a newline to be inserted.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/QgrcJHsbjBtCThLpRmNDcjlkLmVBPrQHhVB

### PR DESCRIPTION
**Pull request by martgil**
This PR re-arrange the processing of newlines in quoted email + remove style which results to "inline divs" that causes issue described in #5740.

close #5740 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Test added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
Hi @sosnovsky - I will also share another custom build with the reporting user to confirm the fix, in addition to my personal verification.

**Comment by martgil** [comment]
To test this one manually, in addition to the updated test:

1. ) Open any secure email on Gmail that the FlowCrypt extension can render.
2. ) Once a secure email from your inbox, click the "..." icon to see the quoted text part.
3. ) On the section where the line "On 202x-01-01 at 12:00, user@example.com wrote:" try to press enter and you'll get the desired newline compare with bugged version where div's after div's is injected due to the "inline-block" css property from the consumer build. The issue that happens when interacting onto the last instance of ">" in the quoted text part is also fixed.

**Comment by martgil** [comment]
Hi @sosnovsky - this one is ready for review. thank you!

**Review by sosnovsky — APPROVED** [review]
Works well 👍

**Pull request merged**
