### PR TITLE
Added separate less strict prompt for ekm user

### LINKED ISSUE #3856: update reset account procedure for EKM users
when EKM is used, going to `flowcrypt settings -> Additional settings -> experimental -> reset account`:

- [x] it should not produce such a stern warning. Instead it should only say `You may lose local settings by resetting this extension. Continue?` and no second confirmation
- [x] debug file that contains the private key should not be saved - this step should be skipped

### PR DESCRIPTION
**Pull request by martgil**
This PR will show add a separate prompt for Ekm users. Additionally, Ekm users will not be able to receive private key backup after the reset.

close #3856 // if this PR closes an issue

----------------------------------

**Tests**
- not worth testing

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
I am getting an error on most test that requires a passphrase. Maybe there is some sort of config that I need based on `Config.key()` that I've missed during the inital setup of the project.

```
(attempt 1 of 1) Failed:   TypeError: Cannot read property 'passphrase' of undefined
          at Function.SetupPageRecipe.recover (/home/mart/project/flowcrypt-browser/test/source/tests/page-recipe/setup-page-recipe.ts:208:69)
          at Function.BrowserRecipe.setUpCommonAcct (/home/mart/project/flowcrypt-browser/test/source/tests/tooling/browser-recipe.ts:60:7)
          at /home/mart/project/flowcrypt-browser/test/source/test.ts:73:9
          at /home/mart/project/flowcrypt-browser/test/source/browser/browser-pool.ts:143:61
          at BrowserPool.withNewBrowserTimeoutAndRetry (/home/mart/project/flowcrypt-browser/test/source/browser/browser-pool.ts:143:11)
          at /home/mart/project/flowcrypt-browser/test/source/test.ts:70:5
          at <async> recover (/test/source/tests/page-recipe/setup-page-recipe.ts:205:26)
          at <async> setUpCommonAcct (/test/source/tests/tooling/browser-recipe.ts:57:34)
          at <async> <anonymous> (../test/source/test.ts:70:53)
          at <async> <anonymous> (/test/source/browser/browser-pool.ts:143:49)
```

**Comment by tomholub** [comment]
Please edit the PR description to follow the template / prompts

**Review by tomholub — CHANGES_REQUESTED** [review]
Before marking a PR as ready for review, please do a self-review first.

Go to PR -> `Files Changed` and see all of the changes you've made, to make sure they all make sense. Once you've confirmed this, then you can mark it as ready for review.

There's some unwanted code left over if you have a closer look. It's better to self-correct this then to rely on the reviewers to tell you.

Please fix. Otherwise it looks good.

**Comment by martgil** [comment]
Understood Tom, I'll be correcting these mistakes.

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
Merging this - ok to skip tests this time, it's pretty minor.

**Pull request merged**
