### PR TITLE
Issue 1881 refactor composer contacts

### PR DESCRIPTION
**Pull request by michael-volynets**
This is another PR from another branch because I force pushed the changes

### CODE REVIEW

**Comment by michael-volynets** [comment]
Sorry about `--force`, I used it because it was the fastest way to remove those re-arranging changes

**Comment by tomholub** [comment]
@michael-volynets for whatever reason the new files all had 4-space indent, but normally we use 2-space indent. My IDE automatically reformatted it with 2-space on save. Maybe check your settings and see if it can be adjusted. (Or project settings that you could check into the repo.)

**Comment by tomholub** [comment]
It is really hard to review refactors like this :( but refactors have to be done. Looks good now.

**Comment by tomholub** [comment]
But it's much better than with the rearranged methods! That was the killer for me.

**Comment by tomholub** [comment]
#1881

**Pull request merged**
