### PR TITLE
#5318 Add ConfiguredIdPOAuth class

### LINKED ISSUE #5318: add skeleton of `ConfiguredIdpOAuth` class
- [x] a new class called `ConfiguredIdpOAuth` that inherits from `OAuth`. It should contain new method called `newAuthPopupForEnterpriseServerAuthenticationIfNeeded`
- [x] The method checks the storage for `authentication` and decides if a custom IdP is used or not. If custom IdP is not used, it just returns `Promise<void>`.
- [x] else it shows a warning modal `Custom IdP is configured on this domain, but it is not supported on browser extension yet. Authentication with Enterprise Server will continue using Google IdP until implemented in a future update.`
- [x] this new method should be called in `newGoogleAcctAuthPromptThenAlertOrForward`, right under `await GlobalStore.acctEmailsAdd(response.acctEmail);` inside the success case
- [x] update the test from earlier issue #5317 to also expect this modal

### PR DESCRIPTION
**Pull request by martgil**
This PR Adds a new class called 'ConfiguredIdPOAuth' and a test for ensuring its effective implementation.

close #5318 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
@martgil is this one ready for review or it's a draft?

**Comment by martgil** [comment]
> @martgil is this one ready for review or it's a draft?

sorry, not yet. I'm just wondering if this could be leave as is one approved without it getting merged?

**Comment by martgil** [comment]
@sosnovsky Ready for review. thank you!

**Review by sosnovsky — APPROVED** [review]
Looks good 👍

**Pull request merged**
