### PR TITLE
Issue #1883 Leave else case empty instead of 'inherit'

### PR DESCRIPTION
**Pull request by michael-volynets**
Issue #1883 
Time Spent: 20m

Yes, sorry, that was my bad,
I don't know why but I thought that `background-color: inherit;` inherits the previous color but it doesn't, it inherits something else (maybe I will investigate it later)

### CODE REVIEW

**Comment by michael-volynets** [comment]
Now, It looks like this:
image

**Comment by tomholub** [comment]
Much better, thanks for taking care of it late at night

**Comment by tomholub** [comment]
Maybe inherit inherits from the parent. Which is white

**Comment by tomholub** [comment]
I removed the screen because it contained user email. Best is to black out any emails present in screen shots

**Comment by michael-volynets** [comment]
No problem, I'm trying to be available anytime :)

Yes, sure, I will black emails next time

**Pull request merged**
