### PR TITLE
Add toast message for dropped pubkeys

### LINKED ISSUE #2763: toast message for dropped pubkeys in compose window
https://github.com/FlowCrypt/flowcrypt-browser/pull/2739#discussion_r423845537

as eg orange bubble, plus possibly modal, and hint how to resolve (manually enter recipient key?)

image

### PR DESCRIPTION
**Pull request by limonte**
Closes #2763

Also, improved UX for toasts a bit to let users know when a toast will be closed and let them pause the timer (e.g. if they need more time to read and understand it) by hovering with a mouse.

MGYudutmcC

### CODE REVIEW

**Comment by tomholub** [comment]
The hover-pause is extremely clever, did you come up with that? Did you see it somewhere? Epic

**Review by tomholub — APPROVED** [review]

**Comment by limonte** [comment]
> The hover-pause is extremely clever, did you come up with that? Did you see it somewhere? Epic

I'm not sure now, but most probably I saw that first time in https://codeseven.github.io/toastr/demo.html

**Comment by limonte** [comment]
> The hover-pause is extremely clever, did you come up with that? Did you see it somewhere? Epic

Also, the next update of `sweetalert2` dependency which will be done by dependabot tonight, will add the ability for users to copy-paste the content of toasts. Currently, they are closed by clicking on them. See https://github.com/sweetalert2/sweetalert2/releases/tag/v10.12.6

**Comment by tomholub** [comment]
Well done

**Pull request merged**
