### PR TITLE
 ui to diagnose faulty keys

### PR DESCRIPTION
**Pull request by tomholub**
addresses #1257

### CODE REVIEW

**Comment by tomholub** [comment]
@schmorrison please address the test fails. You should be able to get the same result when you run `npm run-script test`

```
> flowcrypt-browser@6.6.2 test_tslint /home/runner/flowcrypt-browser
> tslint --project ./tsconfig.json --config ./conf/tslint.yaml && ./node_modules/.bin/tslint --project ./conf/tsconfig.content_scripts.json --config ./conf/tslint.yaml


ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/modules/compatability.ts[95, 27]: Unsafe use of expression of type 'any'.
ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/modules/compatability.ts[118, 67]: Unsafe use of expression of type 'any'.
ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/modules/compatability.ts[118, 73]: Unsafe use of expression of type 'any'.
ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/modules/compatability.ts[147, 61]: Unsafe use of expression of type 'any'.
ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/modules/compatability.ts[151, 67]: Unsafe use of expression of type 'any'.
ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/modules/compatability.ts[199, 7]: Promises must be handled appropriately
ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/modules/compatability.ts[201, 45]: Unsafe use of expression of type 'any'.
```

Unsafe use means when you do something like:
```js
let someString: any;
someString = 'hello world';
someString.split(' ');
```
I don't know if this exact snippet would trigger it, but in general, an 'any' could be anything, eg a number, and doing number.split would cause an exception: not safe.

It's safer to use the `unknown` type with typeguards, or you could cast it to not be any if you know what you're doing.

**Comment by tomholub** [comment]
Handled promises means you have to `await` every promise, else you lose rejections that happen in it.

**Comment by schmorrison** [comment]
Getting a testing error. The file in question is in gitignore file, presumably its provided on the CI test system.

```
  Uncaught exception in build/test/test/source/test.js
  Error: ENOENT: no such file or directory, open 'test/test-secrets.json'
  Object.<anonymous> (test/source/util/index.ts:20:41)
  Object.extensions.(anonymous function) [as .js] (node_modules/require-precompiled/index.js:16:3)
```

**Comment by schmorrison** [comment]
I made another change to the typings to handle one of the `unsafe use of any` errors.

**Comment by tomholub** [comment]
closes #1257

**Comment by tomholub** [comment]
Correct, the secrets file is provided by ci. You will also get one once we sign NDA and stuff like that.

**Pull request merged**
