### PR TITLE
Plain reply to encrypted message

### LINKED ISSUE #1735: Standard reply box gets replaced when you want to send a nonenrypted email.
**editted by Tom with latest issue description to avoid confusion**
----------------------

Existing behavior to preserve:
- if last message is encrypted, and I click encrypted reply, render encrypted reply box
- if last message is plain, and I click plain reply, render plain reply
- if last message is plain, and I click encrypted reply, render encrypted reply

Current unwanted behavior:
 - if last message is encrypted, and I **click plain reply icon on top right**, it still shows an encrypted reply box

Instead, we should find a way to NOT replace the plain reply box that shows **after explicitly clicking on plain reply** and instead augument it with a very bright red box above it, which says: `The last message was encrypted, but you are composing a reply without encryption. [switch to encrypted reply]`

In a separate issue, we should have a way to switch from within the secure reply to replying without encryption.

That should be less invasive and make everyone happy.

### PR DESCRIPTION
**Pull request by limonte**
Closes #1735 

@tomholub is live Gmail test needed for this PR?

### CODE REVIEW

**Comment by tomholub** [comment]
I don't think so, you can just test compose frame individually, set isReplyBox=true

**Comment by tomholub** [comment]
@limonte sorry I got confused. Yes! Please add a Gmail test.

**Comment by tomholub** [comment]
> @limonte sorry I got confused. Yes! Please add a Gmail test.

Also, the PR does not include the warning message - do you think it would be unpleasant?

**Comment by limonte** [comment]
> > @limonte sorry I got confused. Yes! Please add a Gmail test.
> 
> Also, the PR does not include the warning message - do you think it would be unpleasant?

Oops, overlooked that, sorry! It'll be useful, will add it :+1:

**Comment by limonte** [comment]
> Works perfectly, just left an .only behind.
> 
> Finally! This was bothering me every day fireworks fireworks fireworks

:tada: This PR can be reviewed and merged and I can add the

> very bright red box above it, which says: The last message was encrypted, but you are composing a reply without encryption.

in separated PR along with the "[switch to encrypted reply]" functionality.

**Pull request merged**
