### PR TITLE
#5811 Added ability to generate keys in the extension

### LINKED ISSUE #5811: [Feature Suggestion] Ability to generate keys within the extension
Description: The ability to generate keys within the FlowCrypt browser extension can be useful in cases where a user needs to generate a new key for themselves or others.

Ideally, this feature could include additional checkboxes asking whether the key that is about to be generated should be stored and added to the user's key list or not. This would allow users to choose between storing the key for future use or simply generating it for immediate distribution (i.e., generate and forget). Users should also be able to select key types and algorithms during the generation process.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVzFNhdqCqRtGmqlQspMRKxHxD

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR added ability to generate keys in the extension

close #5811 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@sosnovsky Implementation is now finished. Will be adding UI test now.
In the meantime,could you test functionality and let me know if you want some changes?

**Comment by sosnovsky** [comment]
@ioanmo226 I expected this functionality to be added to the existing `Add key` modal, like described in https://github.com/FlowCrypt/flowcrypt-browser/issues/5811#issuecomment-2309848626. Will it be too complicated to move it there?

**Comment by ioanmo226** [comment]
I saw that comment.
But there are only radio boxes in Add key modal. Thought not good UI/UX to add `Generate key` button in there.

**Comment by ioanmo226** [comment]
Let me know if you want to place `Generate Key` button in modal.
If so, do I have to place at the top of radio checkboxes? Should it be button or radio type?

**Comment by sosnovsky** [comment]
Yes, let's place it in the modal as radio button, like other options:

Screenshot 2024-09-06 at 12 31 05

**Comment by ioanmo226** [comment]
If user clicks `Generate new key` button it should replace modal with generate key view?

**Comment by ioanmo226** [comment]
Or display generate key view under the radio buttons?

**Comment by sosnovsky** [comment]
> Or display generate key view under the radio buttons?

It should appear below radio buttons, so users will be able to switch between different options:

Screenshot 2024-09-06 at 14 34 45

**Comment by ioanmo226** [comment]
I see. Let me implement that way

**Comment by ioanmo226** [comment]
Ohhh. Yep
That's it.
It would be because I added new test `settings - my key page - generate key` which generated new key.

**Comment by ioanmo226** [comment]
Thank you for your hin

**Review by sosnovsky — APPROVED** [review]
Well done, works great 👍

**Pull request merged**
