### PR TITLE
issue #714 pop out/maximize secure compose window

### PR DESCRIPTION
**Pull request by lyova98**

### CODE REVIEW

**Comment by tomholub** [comment]
@lyova98  Hello, this does not address the issue, which was to **add** (not replace) a fourth button that would come with new functionality to pop out / maximize the compose window, similar to what Gmail does:

image


image

And back to normal size if I click on it again.

**Comment by lyova98** [comment]
@tomholub as I understand the task is change the maximize icon to the left of close icon □

**Comment by tomholub** [comment]
No, the task is to add a new icon, similar to the one in Gmail, and implement similar functionality to what Gmail does.

**Comment by lyova98** [comment]
@tomholub so I have changed the icon  □  to like in gmail, now I need to add functionality like in gmail for resize window icon like in gmail right?
https://prnt.sc/n7k6s1

**Pull request closed without merging**
