### PR TITLE
Issue #1741, Changed text and corrected quoting algorithm

### PR DESCRIPTION
**Pull request by michael-volynets**
Issue #1741 
Time Spent: 1h 15m

### CODE REVIEW

**Comment by michael-volynets** [comment]
Do you mean to add exactly the same text as when we're replying to some message?

**Comment by tomholub** [comment]
Yes, I don't see any reason not to :) When you forward a message, you want to know what the other person said and when.. and we already have a mechanism for that. I'd reuse the same.

**Comment by michael-volynets** [comment]
Okay, sorry then, I didn't catch it from the first time.

**Comment by michael-volynets** [comment]
Done

**Pull request merged**
