### PR TITLE
Added reauth tests on uuid change

### LINKED ISSUE #2703: Write a backend re-auth test (eg when user revokes session)
Write a backend re-auth test as follows:

1) set up acct
2) Additional settings -> experimental -> Set a new randomly generated FlowCrypt Account UUID
3) open settings, notice modal prompt to re-auth
4) re-auth
5) no more modal in settings

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/2702#issuecomment-605492242_

---------------------------

I'm not entirely sure if our mock backend actually looks at the uuids or ignores them. If it's ignoring them (more likely), we'd have to add functionality where the backend actually saves and remembers uuids.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Closes #2703

### CODE REVIEW

**Review by tomholub — DISMISSED** [review]
Thanks!

**Comment by tomholub** [comment]
Actually I'd be ok to skip the Gmail live test on this one, mock should be enough. Unless you ran into a scenario that you think should be tested on Gmail too.

**Comment by rrrooommmaaa** [comment]
> Actually I'd be ok to skip the Gmail live test on this one, mock should be enough. Unless you ran into a scenario that you think should be tested on Gmail too.

It ran fine on my computer, so I don't know of such scenario. Perhaps, there should be a sleep timeout adjust. Should I comment it out or remove it completely?

**Review by tomholub — APPROVED** [review]
I'll merge it, and we'll probably eventually remove it

**Pull request merged**
