### PR TITLE
Remove pubkeys from contacts #3632

### LINKED ISSUE #3632: [Settings / Contact list] Unable to remove contacts
These buttons don't seem to work:

image

While fixing
 - add `title` attribute to all buttons (View, Edit, Remove), 
 - fix the buttons height which is currently a bit off:

image

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
This PR allows to remove a pubkey from a contact (email).
When a pubkey is no longer referenced by any email, it is deleted from the store.

close #3632

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by rrrooommmaaa** [comment]
The added test checks both UI side and disappearance of pubkeys from the store.
Do we need to add a dedicated test to `unit-ContactStore.js` and/or a test checking that no exception is thrown when a non-existent email/keyid are supplied?

**Review by tomholub — APPROVED** [review]
Thanks!

**Comment by seisvelas** [comment]
Sorry to bug, but any idea when this will be released in a version users can upgrade to? I'm eager to respond to some emails  from users who asked to be updated when this is released with good news :)

**Comment by tomholub** [comment]
On Firefox, it's already released. On Chrome, I'm doing a 20% release now (which may take a day or two to be verified, and then another week before I bump it to 100%).

**Comment by tomholub** [comment]
It's / will be version 8.1.0

**Pull request merged**
