### PR TITLE
issue 4983 change CSP to allow loading remote images

### PR DESCRIPTION
**Pull request by tomholub**
This PR attempts to fix loading remote images.

issue #4983

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests will be added later

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
I've tested this change by just manually adding an img tag. It didn't work on master, but works now.

@ioanmo226 could you please test it on the original customer sample?

image

**Comment by ioanmo226** [comment]
Hmmm.. Just tested.
But still it doesn't work for customer sample. Still returns CORS error

**Comment by ioanmo226** [comment]
Access to fetch at 'https://domain.com/logo.png' from origin 'chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ioanmo226** [comment]
I think loading image through our api won't trigger security if we don't store any data on our server?

**Comment by tomholub** [comment]
Where can I find it? I tested this:

image

image

**Comment by tomholub** [comment]
> I think loading image through our api won't trigger security/privacy if we don't store any data on our server?

Our users would have to trust us that we wouldn't have a peek at it, defying the whole point of our business.

**Comment by ioanmo226** [comment]
> Where can I find it? I tested this:

Just sent you email (.eml file customer shared)

**Comment by ioanmo226** [comment]
> > I think loading image through our api won't trigger security/privacy if we don't store any data on our server?
> 
> Our users would have to trust us that we wouldn't have a peek at it, defying the whole point of our product/business.

I see

**Comment by tomholub** [comment]
How did you load the `.eml` email into your Gmail inbox? I used Thunderbird before, wonder if you have an easier way.

**Comment by ioanmo226** [comment]
I'm currently using Apple mail app.
When I double-clicked .eml file, apple mail opened. 
And then I have to click `Move to inbox` button. (That's all)

image

**Comment by sosnovsky** [comment]
> Seems to work when I replace an `img` `src` with the customer url `https://REDACTED/rs/REDACTED/images/REDACTED.png`

Yes, `CORS` error doesn't occur when image is loaded with `` tag.
It happens when we try to download image data and get `base64` from it.

**Comment by tomholub** [comment]
> > Seems to work when I replace an `img` `src` with the customer url `https://REDACTED/rs/REDACTED/images/REDACTED.png`
> 
> Yes, `CORS` error doesn't occur when image is loaded with `` tag. It happens when we try to download image data and get `base64` from it.

Alright, so I suppose what we did was backwards after all.

We should stick to `` tags. Remove the csp restriction as I've just done, and all of the images will work, regardless of CORS.

**Comment by ioanmo226** [comment]
Does it mean we have to revert https://github.com/FlowCrypt/flowcrypt-browser/pull/4994 and remove the CSP restrictions?
Are you okay with removing CSP restrictions?

**Comment by tomholub** [comment]
I didn't entirely remove CSP of course, but I did adjust it to allow remote images from any source.

Whether we load images directly through `src` tags, or whether we download them from AJAX and load the data in, I don't see much of a security difference. So I propose to update the CSP as I've done here.

Yes, I'd revert it.

**Comment by ioanmo226** [comment]
Okay, Yeah

**Comment by tomholub** [comment]
I'd still like to continue to clearly frame images to make it clear they are framed, plus if the image is remote, I'd like a warning inside of that box/frame just above the image: `Authenticity of this remote image cannot be verified.`

**Comment by tomholub** [comment]
@sosnovsky does this sound ok to you? Want to run this by you to make sure.

**Comment by sosnovsky** [comment]
> @sosnovsky does this sound ok to you? Want to run this by you to make sure.

Yes, it's ok, as it seems no other way to make remote images work well in encrypted messages.

**Comment by tomholub** [comment]
I'll let the customer know

**Comment by ioanmo226** [comment]
What do you mean clearly frame images?
You mean add border to remote images?

> I'd still like to continue to clearly frame images to make them stand out

**Comment by tomholub** [comment]
> What do you mean clearly frame images? You mean add border to remote images?
> 
> > I'd still like to continue to clearly frame images to make them stand out

I think we already border all images, with a css border.

I'd like something similar, like you have done for the error handling:

image

Except that instead of `Failed to load image` there would be the `Authenticity of this remote image cannot be verified.` and below that, there would be the actual image.

**Comment by tomholub** [comment]
Sorry, I got confused. Apparently we no longer put a css border around images. I think we used to do that? Nevermind that.

Anyway, for remote images, please do as described here: https://github.com/FlowCrypt/flowcrypt-browser/pull/4999#issuecomment-1458420141 which you should be able to reuse existing code for.

**Pull request closed without merging**
