### PR TITLE
#5304 Move pgpMsgDecrypt and pgpKeyBinaryToArmored to content script

### LINKED ISSUE #5304: Re-enable BrowserMsg.addPgpListeners() if needed
We have a couple comments saying `// BrowserMsg.addPgpListeners(); // todo - re-allow when https://github.com/FlowCrypt/flowcrypt-browser/issues/2560 fixed`:
- https://github.com/FlowCrypt/flowcrypt-browser/blob/c5e719146092df0b90b4418792ff5fac45872142/extension/chrome/settings/inbox/inbox.ts#L107
- https://github.com/FlowCrypt/flowcrypt-browser/blob/c5e719146092df0b90b4418792ff5fac45872142/extension/js/content_scripts/webmail/webmail.ts#L153

https://github.com/FlowCrypt/flowcrypt-browser/issues/2560 is closed, so we can re-enable this code, if it's still needed after reworking decryption process.

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR moves `pgpMsgDecrypt` and `pgpKeyBinaryToArmored` functions to content script

close #5304

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
Hi @martgil, this PR moves some code from background page to content script (as part of bigger task for migrating to Manifest V3 https://github.com/FlowCrypt/flowcrypt-browser/issues/1509), as in Manifest V3 background pages are not supported. It's ready for review, thanks!

**Comment by martgil** [comment]
I'll review it now. Thanks, Roma.

**Review by martgil — CHANGES_REQUESTED** [review]
@sosnovsky I checked the code and I noticed that the background message `pgpKeyBinaryToArmored()` is no longer in use. Perhaps it can be removed too?

**Comment by sosnovsky** [comment]
> @sosnovsky I checked the code and I noticed that the background message `pgpKeyBinaryToArmored()` is no longer in use. Perhaps it can be removed too?

Yeah, you're right, missed it, thanks for noticing!

**Review by martgil — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
