### PR TITLE
#4693 fix: issue reconnecting authentication on existing installation

### LINKED ISSUE #4693: issue reconnecting authentication on existing installation
Experienced on Firefox, but I suppose it could be cross-browser.

1) set up extension on previous version with OOB
2) update extension
3) open secure compose
4) I get prompted to reconnect

image

5) I follow the link, but I leave some checkboxes unchecked

image

6) result:

image

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed reconnecting authentication on existing installation issue

close #4693 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@tomholub 

I think we can't display modal (like in setup screen) because we use content script in gmail page and to display modal we have to include so many files and that seems messy.
Because of that, I displayed web notification.
> It could be a modal or it could be a notification like the one above, see what works better.

Hmm... not sure how we can achieve `reconnect auth popup` and extension update in mock test.
> I'm suggesting that this could be tested with a mocked Gmail page, shouldn't need live test to test it.

**Review by tomholub — COMMENTED** [review]
👍 implementation looks good

**Comment by ioanmo226** [comment]
how about my question regarding test?

**Comment by ioanmo226** [comment]
This one seems hard to test even with live gmail test.

**Comment by tomholub** [comment]
Notice `getMockGmailPage`, served at `TestUrls.mockGmailUrl()`

Extract this code into a method `wipeGoogleTokensUsingExperimentalSettingsPage`

```ts
      // below test that can re-auth after lost access (simulating situation when user changed password on google)
      for (const wipeTokenBtnSelector of ['@action-wipe-google-refresh-token', '@action-wipe-google-access-token']) {
        const settingsPage = await browser.newPage(t, TestUrls.extensionSettings(acct));
        await SettingsPageRecipe.toggleScreen(settingsPage, 'additional');
        const experimentalFrame = await SettingsPageRecipe.awaitNewPageFrame(settingsPage, '@action-open-module-experimental', ['experimental.htm']);
        await experimentalFrame.waitAndClick(wipeTokenBtnSelector);
        await Util.sleep(2);
        await settingsPage.close();
      }
```

This is from a live test `mail.google.com - success notif after setup, click hides it, does not re-appear + offers to reauth`, where you can also use this method.

Then you'll want to edit `OauthMock` to have add maybe `setAccountSpecificBehavior(acct, 'INSUFFICIENT-PERMISSION')` method or similar. Then also `setAccountSpecificBehavior(acct, undefined)` to reset it.

The actual test steps would be approximately as follows:
1) set up extension just like any other mock test
2) use the new `wipeGoogleTokensUsingExperimentalSettingsPage`
3) navigate to `TestUrls.mockGmailUrl()`
4) you should see the notification pop up. If it doesn't, you'll want to debug what is needed for the notification to show in mock gmail page
5) set `oauthMock.setAccountSpecificBehavior(acct, 'INSUFFICIENT-PERMISSION')`
6) click on the "reconnect" notification
7) notice it will show you the modified notification (need more permissions)
8) set `oauthMock.setAccountSpecificBehavior(acct, undefined)`
9) click on the add permissions link
10) notice a succesful notification
11) refresh the mock gmail page, should show no notification

It's not the easiest, but I don't have any better idea.

**Comment by ioanmo226** [comment]
Got it
Thank you for your brief explanation

**Comment by tomholub** [comment]
Oh, there should be a try/finally block like this:

```ts
try {
  // 5 - oauthMock.setAccountSpecificBehavior(acct, 'INSUFFICIENT-PERMISSION');
  // 6 - click on the "reconnect" notification
  // 7 - notice it will show you the modified notification (need more permissions)
} finally {
  // 8 - oauthMock.setAccountSpecificBehavior(acct, undefined);
}
```

That way, if the test fails, it won't affect the next retry of the test. Then finally, make sure to use some unique account email not used in other tests, so it doesn't affect other tests when run in parallel.

**Review by tomholub — APPROVED** [review]

**Pull request merged**
