### PR TITLE
use options_ui in manifest.json file

### LINKED ISSUE #4415: Usage of deprecated options_page in manifest.json
affected file: https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/manifest.json#L72

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_page

solution: update the manifest file using options_ui as an alternative.

image

An error message like I mentioned on https://github.com/FlowCrypt/flowcrypt-browser/pull/4394 started to work more appropriately after the update. I tried testing it locally. eg. From 'Bad Format...' to 'Error: could not properly parse signed message...' (might be coincidence 😮‍💨).

It's best when we are using non-deprecated property.

reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGpFgmKwsFhjdgvVmGqDThsdGbb

### PR DESCRIPTION
**Pull request by martgil**
This PR will update the manifest.json file to use options_ui

reference: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui

close #4415  // if this PR closes an issue

issue #0000 // if it doesn't close the issue yet

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
@tomholub 

> How about chrome - could you check the documentation there too?

based on https://developer.chrome.com/docs/extensions/reference/browserAction/, the properties were using is not yet deprecated.

I have faced some issue that needs helps - https://github.com/FlowCrypt/flowcrypt-workspace-key-manager/issues/338

**Comment by tomholub** [comment]
I was talking about the "URI filtering" email.

**Comment by tomholub** [comment]
I mean, is `options_ui` supported in chrome? If you are replacing `options_page` with `options_ui` then you'll want to double check it's not breaking existing functionality on chrome.

**Comment by martgil** [comment]
@tomholub works fine on both Chrome and Firefox browsers after adding another property "open_in_tab: true".

**Comment by tomholub** [comment]
You have to be careful with this. Properly checking that your update works across all the needed contexts (in this case chrome vs firefox) is what differentiates a junior developer from others.

In this case, it was recognized in the review process, but you have to have your own initiative to check for that first.

**Comment by tomholub** [comment]
@rrrooommmaaa please see if this looks ok

**Review by rrrooommmaaa — APPROVED** [review]

**Pull request merged**
