### PR TITLE
Issue 1530 reply button non encrypted email

### PR DESCRIPTION
**Pull request by michael-volynets**
#1530 

image

### CODE REVIEW

**Comment by tomholub** [comment]
This is not bad. I was imagining to put the encrypted reply button on the bottom, but actually I think what you have done is better.

Maybe in this case we can stop adding the "secure reply" button on the top right, as it's redundant.

Secondly, the new button behaves weirdly when hovered, it will get bigger/smaller as I hover, disturbing surrounding buttons.

Thirdly, it seems to look a bit out of place (I know it's our own icon :) ), maybe we could redesign it. Maybe we could use the original Gmail icon, but in green color, and with a lock next to it. Then it will blend with the rest of Gmail better.

I can supply the icon if you like.

**Comment by michael-volynets** [comment]
Okay, got it.
I will do it. Provide me the icon if you can

**Comment by tomholub** [comment]
Just noting here that we talked over email that you'll give it a try to create that icon

**Comment by michael-volynets** [comment]
Should the reply button be in all messages blocks or only in the last one?
image

Because  In the code I found that it tries to add it to each message block

**Comment by tomholub** [comment]
You've done a great job here!

I especially like that I can click "encrypted reply", then change my mind and click "normal reply" instead, and it will work - I think it didn't work before and I really like to see it working. Not sure what you did there, but it really helped.

If you click encrypted -> normal reply -> encrypted -> normal (change your mind several times), it will get stuck on encrypted, similar to before. But that's not so bad, this situation should be a lot rarer.

How do you make svg icons? Which software do you use? It's good but the lock turned out very small. I'll open another issue for this.

Lastly, it's missing a title that normally shows over other gmail buttons when you hover over them. I'll add the title after I merge it.

**Pull request merged**
