### PR TITLE
Add the ctrl+\ shortcut for removing the formatting

### PR DESCRIPTION
**Pull request by limonte**
This PR allows users to remove the formatting with the keyboard to give the ability to remove styles from the pasted text.

issue #3347 (not close because I'd like to figure out the button for removing the formatting as well)

### CODE REVIEW

**Review by tomholub — COMMENTED** [review]
Does this remove formatting from just the selected text, or the whole textarea?

**Comment by limonte** [comment]
> Does this remove formatting from just the selected text, or the whole textarea?

Just selected text.

**Comment by limonte** [comment]
> > Does this remove formatting from just the selected text, or the whole textarea?
> 
> Just the selected text.

This is aligned with Gmail. My idea is to keep shortcuts and their actions as close as possible to Gmail.

**Review by tomholub — APPROVED** [review]
Thanks!

**Pull request merged**
