### PR TITLE
issue-1649 Changed download text and made the whole block clickable

### PR DESCRIPTION
**Pull request by michael-volynets**
How it looks like:

image

### CODE REVIEW

**Comment by tomholub** [comment]
If you take a look at the test failure at https://semaphoreci.com/flowcrypt/flowcrypt-browser/branches/issue-1649-right-clicking-on-attachment/builds/1 , you'll see:
```
> flowcrypt-browser@6.7.4 test_patterns /home/runner/flowcrypt-browser
> node build/test/test/source/patterns.js

unchecked xss in extension/js/common/browser.ts:66:
        a.innerHTML = '<div>Right-click here and choose \'Save Link As\' to save encrypted file</div>';

patterns.ts: Found 1 unhandled patterns, exiting
```
Our code checkers don't like to see innerHTML because it is easy to cause xss vulnerability (not in your case, but in general).
Since you are adding the content there straight from a string (and not from variable) you can add ` // xss-direct` comment at the end which should suppress the code check on that line.

**Comment by michael-volynets** [comment]
oh, okay, got it, 
I forgot to run tests before doing the pull request.

**Comment by tomholub** [comment]
No worries, that's what CI is for.

**Comment by tomholub** [comment]
#1649

**Pull request merged**
