### PR TITLE
use Content-Transfer-Encoding:7bit for pgp-keys and PGP/MIME attachment

### LINKED ISSUE #4283: wasteful encoding of encrypted attachments in mime
When sending password-protected message, currently, we armor the encrypted data and then we base64 encode it.

Armoring also includes base64, and so we double-base64 encode it in the end.

It would be better to only encode once, if we can still produce a validly formatted message that way. This is browser:

```
------sinikael-?=_1-16432713087950.5202698292190784
Content-Type: application/octet-stream; name=encrypted.asc
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename=encrypted.asc
X-Attachment-Id: f_VAPSRsspZNAlSauwuyhZpynklUNAXd@flowcrypt
Content-Id: <f_VAPSRsspZNAlSauwuyhZpynklUNAXd@flowcrypt>
Content-Transfer-Encoding: base64

LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tDQpWZXJzaW9uOiBGbG93Q3J5cHQgRW1haWwgRW5j
cnlwdGlvbiA4LjIuNA0KQ29tbWVudDogU2VhbWxlc3NseSBzZW5kIGFuZCByZWNlaXZlIGVuY3J5
cHRlZCBlbWFpbA0KDQp3VjRERTRuUDM4SWwwaDRTQVFkQWN5eFJlbndqd1llTUR5dXNNMk9FeWhy
L0tkTTBMQ0s0ZlUwaE44cTcNCjQya3dvaGwwN0tLQ2tKV0tZM1VXSnQ4ZWM1TUh0Wld5SFdWR1Ez
eW9hWlB0VEkzN1FMTFJxSi82V3FxcA0KWmUrdHlkK0kwc0ppQVNpZktHZ2JUeFBMa1J5SkdsdDEz
REV1c05NYmlUM3d4azZjdS9oWjdJeGsrUU1uDQozY0t1QXllQXJHMUZZbkVyd3VFUlU1dHhMaTBQ
cjRxdDNTa2RvWWU2aGQzYTBGSEEwdmlGcTJYcnJYTjkNCjVERFdUanFoanIzU09mMm9NdXlsTm4y
WWZEY2FoZ3FJbzdkbVA3STVMYVFBUHRsTHhHRytLNmk3RFpSWA0Ka3VKZXBBQ3J4V1BjRmhRV2lv
UEw2VVRnS2NLMzRWWjNnWk1oMUNzWFRYMi90S3NLRGtxbjlwTHVhV1JxDQpqUnUzL0t2MkVXMms4
TVVJZ3BWRXpydTMzQ2cvT1NmM09VZDdQV2c0eXFIZkN2YmI3ZEl3US9UYzlvOTcNCkxhVmlVeDJB
c0VEbXMrd3NhaXJ2OElWQkRnbFp1WmF4bFI1THR2K3pMTGtnL3Azd2pQcGQvYlFUYmxjeA0KZXBY
a0RzQlJJZzV6enF5VlhYY1BCVDMwMlJ1QkxCaEcvVXJLczgraUZJU0lQbWFNYjd5a0dmcFRSVC9C
DQpZOUFHL09rNEhUN2praWdUQjY2Zk9qVlJXQmVDVUl3UldBYmY5aG5USFFKSXlNL3BwYnRaN0x2
cWFlTmUNCk5DS0kvY25HdUpadHlhQWN2QVJkc3BtT1l1RDNuSWtaTERoaDNmTnFDd3RRR2FNcW9u
OTRYVlp3dU5OOA0KQVExaG8wU1hoSjVtU2t3bFZjQ2taYWxJKzRQZ0xmK2hkdWp4WXVMUFdlQWhs
K2dZelJiS0p5R1RpZkQ5DQpDZFZpM3pUZXpqaG5iRERhK0dqMEJmQk56S0wxQ2pMOEtkeDFsa0ZT
S1lMNVp2MndDTnBGMHhkNCs5NmwNCkRJdzZDU0FIa3VkWXMvK054WTdUbnQ5SFlBNS9rWWEzU0hw
eHlwN3I1OGwvWEVwdDlIY0pDRUVlRGp2Tg0KcGRySVJOV3VGWnJncUUvL2RpamFtTUd2eXhFN3Yy
U2pmSFBhOGdTOTZWTWRhZ1M4b1pJalJWcVpiOXFqDQpKUmdVNE92LzZDazNIQXQ3bCtDVWc5QUZD
ZTA0Q2ViSHFPc01nL09nVmt5bGdHRkFETm9DdUg0UFZJLzUNCjdmWWtMK3N4dnBhTVp1aE1PSE1U
enFBUUpqMEFtazYxdDR2dm1TcTc4SWFjNWRTN3RPSGRYeWdCSGJYbw0KRCsyNDZGbk9xdjJZakMr
a1lFSHBJVkFJOE4xdnZoU2JldkZ2N3g2WVh1ekl6bXNkTTBwb2xVdzBZYTliDQpYSzVIWXg5bkFF
b0VkemNyS1RlZ1hHR1c4OTMwWGx1bnBsUGZlY0t0T2RhcnphdWRWd3k1dEVBVnVabTYNCkpHZ1M3
c3lwZXBQVlV2VEMrUWZVdGZ1c3ZIKzN1K2JGaXV3QlFJNDlBaStKNmx0cFlTSEFQOVI3cnpicA0K
RVE9PQ0KPVJsd3UNCi0tLS0tRU5EIFBHUCBNRVNTQUdFLS0tLS0NCg==
------sinikael-?=_1-16432713087950.5202698292190784--
```

Android does it better (7bit used here)

```
------=_Part_10_1347953.1643274037349
Content-Type: application/pgp-encrypted; name=message.asc
Content-Transfer-Encoding: 7bit
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename=message.asc

-----BEGIN PGP MESSAGE-----
Version: PGPainless

hF4DE4nP38Il0h4SAQdAqcd3EtTvtyrPpFlx10l+fRWKJB5yE5bd0AkIjx2pdHEw
krUGVlQBcrrifbE5AFzOt2Y4fLT8MpsIGuYTsRSXbZSfVxoiZ3INI4bCvPBtwOyC
0sCXAcNs+sP/SqTjHbmYDFqN+zrf5NkJqUbe0t6wOWtGzIEPkS9gXGzXivzWRL3e
Kauf+Yz0OKSFIbjdEsb7dFdrZUUoDnyQfjvMHr77f+Iw1utjrbxO/uf1hEcorCKY
0wK+nJdU6ha33JrtcfKuURvPYLRdgtHW6v3ZbUOkxQeMM9MUhGBMSu5gfbOEGNOW
sUYrxDPXjLjIqFj96TLXggp7ShVXRGQE4kO0etC8d9XENw/d++3aHnW8IFsXpNY7
hC0TAylGzjmo6sOGEk0IK0PfaH93n1zzTxKJm/9yBPtvjqnI5C16tDdxQS5JtxTu
q3iXyOtYhrj8idXGl83pgrbbGaTdmdx4+oiFeSDgMl36PBXpuaoQcHHp345hczWb
kfKIdM1YmKpHhjR/NLAzxGCHJDGHs/zACtuwNH2TVwlOjAU+UHAtDs+uEHky/Emt
fVxsBjA2/gVZ2A==
=/7dw
-----END PGP MESSAGE-----

------=_Part_10_1347953.1643274037349--
```

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
This PR replaces base64 encoding with 7bit for armored pgp-key and pgp/mime message

close #4283

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
What is the maximum attachment file size that can be sent this way, currently, using inline pgp?

And how about when using pgp/mime (firefox rich text) ?

**Comment by rrrooommmaaa** [comment]
This PR only affects PGP/MIME (richtext) messages and attached keys

**Comment by rrrooommmaaa** [comment]
I mean, the main message body goes to a MIME attachment and Content-Transfer-Encoding for this attachment is set to 7bit.

If you're asking about file attachment, they are not armored, so Content-Transfer-Encoding:`base64` is quite suitable there.

**Comment by tomholub** [comment]
> This PR only affects PGP/MIME (richtext) messages and attached keys

what is currently the largest file that can be sent this way?

**Review by sosnovsky — COMMENTED** [review]
Are there any improvements in messages size?

I tried to send same password-protected message from `master` branch and here - size was the same.

**Comment by rrrooommmaaa** [comment]
> I tried to send same password-protected message from `master` branch and here - size was the same.

This PR only affects PGP/MIME (richtext) messages and attached keys

**Comment by sosnovsky** [comment]
Hmm, maybe I'm missing something but as I understand #4283 task was to reduce password-protected message size by removing additional base64 encoding.

I tried to send password-protected pgp/mime message from firefox extension - size was the same for `master` and for this branch.

**Comment by rrrooommmaaa** [comment]
> what is currently the largest file that can be sent this way?

test case 1. as in test `compose - with attachments + nopgp` non-richtext, nopgp recipient, pubkey-encrypted message to oneself -- no files are present in the sent message

I'll try other test cases shortly....

**Comment by rrrooommmaaa** [comment]
> Hmm, maybe I'm missing something but as I understand #4283 task was to reduce password-protected message size by removing additional base64 encoding.

password-protected messages are not sent, they are uploaded to the backend.
Are we talking about sending to gmail or uploading to backend?

**Comment by rrrooommmaaa** [comment]
Uploaded message looks like this:
```
Content-Disposition: form-data; name="content"; filename="encrypted.asc"
Content-Type: text/plain

-----BEGIN PGP MESSAGE-----
Version: FlowCrypt Email Encryption 8.4.2
Comment: Seamlessly send and receive encrypted email

wy4ECQMIbvzOCLjIcbHg5moOGg8OwsdJqQfkiJR0wBAlI/GNwGlmUOKt9Waq
lo2n0v8AAGmaAUQZFy7TUTzbFc8p7de19vPCcM9bwbxkm8ZSP8K0+X/Frw5u
...
```

So it is 7bit.
 
Or are you worried about attachments in the MIME message encrypted inside this message?

**Comment by sosnovsky** [comment]
> Are we talking about sending to gmail or uploading to backend?

I meant message data uploaded to backend


> Uploaded message looks like this:
> 
> ```
> Content-Disposition: form-data; name="content"; filename="encrypted.asc"
> Content-Type: text/plain
> 
> -----BEGIN PGP MESSAGE-----
> Version: FlowCrypt Email Encryption 8.4.2
> ...

I tried to upload the same message (pgp/mime with attachment) from `master` branch and it looked the same and had the same size (while using `base64`, not `7bit`).

That's why I asked what improvements bring changes from this PR? (as I thought message size with 7bit will be smaller)

**Comment by rrrooommmaaa** [comment]
> I tried to upload the same message (pgp/mime with attachment) from `master` branch and it looked the same and had the same size (while using `base64`, not `7bit`).

Kindly provide samples and places where you see `base64`

**Comment by sosnovsky** [comment]
> Kindly provide samples and places where you see `base64`

I used build from `master` branch, it still uses `base64`, right? And compared it to build from this PR, which uses `7bit`

This is how I compared:
1) compose password-protected pgp/mime message with inline image attachment (attachment size = 14kb)
2) send it
3) open this message on recipient side
4) check `encrypted.asc` size

In both builds `encrypted.asc` size is 26kb, while I expected it'll be smaller with `7bit` encryption

Please correct me if I'm testing it wrong or it's expected result and message size shouldn't change

**Comment by rrrooommmaaa** [comment]
> In both builds `encrypted.asc` size is 26kb, while I expected it'll be smaller with `7bit` encryption

It's not a problem to have armored `encrypted.asc` (that is, it contains `-----BEGIN PGP MESSAGE-----`...)
`7bit` affects `.eml` size, you should check if `encrypted.asc` takes least possible space inside `.eml`, or to be more exact, `-----BEGIN PGP MESSAGE-----` is clearly visible inside `eml`. If we use `Content-Transfer-Encoding: base64`, then `-----BEGIN PGP MESSAGE-----` won't be visible inside `eml` because it'll be encoded again 3 bytes to 4.

**Comment by rrrooommmaaa** [comment]
For not armored attachments it's ok to use `base64` Content-Transfer-Encoding, because if they were not armored at the cryptographic message level, we should armor them at MIME message level

**Comment by sosnovsky** [comment]
Thanks for explanation! I re-tried to send password-protected message, downloaded `.eml` from recipient's gmail but it's still showing `base64` encoding:

Screenshot 2023-02-22 at 11 41 13

Can you please describe which steps will give me `7bit` encoding?

**Comment by rrrooommmaaa** [comment]
> Can you please describe which steps will give me `7bit` encoding?

I can only find 2 places in code where `encrypted.asc` filename is assigned, in `formatEncryptedMimeDataAsPgpMimeMetaAttachments` -- `7bit` is specified there explicitly and is covered by unit tests in this PR,
the other one is `webPortalMessageUpload` -- but this is unrelated to gmail.
The boundary in your sample looks suspicious, should  be `----sinikael...`. The message may have been reformatted as of #3032.

If you provide exact steps to reproduce, I can see the message as it is when it just leaves the browser, but I don't think there is something to catch there.

**Comment by sosnovsky** [comment]
I compared sending the same email in Android and from web extension - it's password-protected message with attachment.
Then I downloaded `.eml` of received messages from gmail.

Message sent from android:
```
------=_Part_0_157227634.1677138543092
Content-Type: application/pgp-encrypted; name=message.asc
Content-Transfer-Encoding: 7bit
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename=message.asc

-----BEGIN PGP MESSAGE-----
Version: PGPainless

hF4Dpgz2VmDrMXISAQdA1wlcwHfovh252kC4hSy5HJ/MBakKTCe8U/PszYsQzA0w
dbZYoSRM5Fi2n3MuGtCnxCKGQCsgHOM6NXXrksySYcJqNr+7UvXSEfOb/hYFILZ0
0sAEAQJMGGLWWyvhWbiIMn3QhC6HpstEyAwF3WxVVTMmzQxIPV3/MJAM2OCC0oN3
...
```

Message sent from web extension:
```
--00000000000001fa8605f5597dc7
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Disposition: attachment; filename="encrypted.asc"
Content-Transfer-Encoding: base64
Content-ID: <f_tgYWzeMNRHSBrMASlGcFTHIqDmbDpx@flowcrypt>
X-Attachment-Id: f_tgYWzeMNRHSBrMASlGcFTHIqDmbDpx@flowcrypt

LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tDQpWZXJzaW9uOiBGbG93Q3J5cHQgRW1haWwgRW5j
cnlwdGlvbiA4LjQuMg0KQ29tbWVudDogU2VhbWxlc3NseSBzZW5kIGFuZCByZWNlaXZlIGVuY3J5
cHRlZCBlbWFpbA0KDQp3VjREcGd6MlZtRHJNWElTQVFkQXQ4VFJBV1VXNWR4dG9oWk5GV244WW9M
```

So it's the same as in original issue description.

**Comment by sosnovsky** [comment]
As I understand, additional base64 encoding should be removed for all password-protected messages. So each password message sent from web extension should be plain `-----BEGIN PGP MESSAGE-----...` (as it currently in messages sent from android) and not base64 string.

Please correct me if I'm wrong

**Comment by rrrooommmaaa** [comment]
> --00000000000001fa8605f5597dc7

This doesn't look like a boundary generated by `emailjs-mime-builder`. The message was likely reformatted by gmail.
Kindly provide the whole message sent by Android, with all the headers etc.

**Comment by rrrooommmaaa** [comment]
> So it's the same as in original issue description.

In the original issue description it was `------sinikael-?=_1-16432713087950.5202698292190784`

**Comment by rrrooommmaaa** [comment]
> As I understand, additional base64 encoding should be removed for all password-protected messages

Password-protected messages are not sent by e-mail, so the issue was about something else. Probably about pubkey-encrypted messages that accompany password-protected messages.
I think this PR solves it.

**Comment by sosnovsky** [comment]
> This doesn't look like a boundary generated by `emailjs-mime-builder`. The message was likely reformatted by gmail.
> Kindly provide the whole message sent by Android, with all the headers etc.

I sent you email with both messages - from android and web extension, maybe they'll help

**Comment by sosnovsky** [comment]
> Password-protected messages are not sent by e-mail, so the issue was about something else. Probably about pubkey-encrypted messages that accompany password-protected messages.

Yes, I'm talking about pubkey-encrypted message which has `encrypted.asc` attachment (just calling it password-protected message), and it's still has `base64` for me. So I'm trying to find how I can see where we're using `7bit` now

**Comment by rrrooommmaaa** [comment]
> So I'm trying to find how I can see where we're using `7bit` now

This hook is activated by a number of tests (we'd be better to start defining these hooks in the test body via the mockApi configuration) .
https://github.com/FlowCrypt/flowcrypt-browser/blob/8dc8e25f8a0db704b202f89f6c313bc094727d6b/test/source/mock/google/strategies/send-message-strategy.ts#L54

e.g. `compose - with attachments + nopgp`
this is how the message looks like:
```
Content-Type: multipart/mixed;
 boundary="----sinikael-?=_1-16771567141240.768917928385471"
Openpgp: id=9BA39CE075F0839B30340FC807481C8ACF9D49FE
From: First Last <ci.tests.gmail@flowcrypt.test>
To: human+nopgp@flowcrypt.com
Subject: Automated puppeteer test: with files + nonppg
Date: Thu, 23 Feb 2023 12:51:54 +0000
Message-Id: <1677156714124-f8ac8769-2241f96b-16416999@flowcrypt.test>
MIME-Version: 1.0

------sinikael-?=_1-16771567141240.768917928385471
Content-Type: multipart/alternative;
 boundary="----sinikael-?=_2-16771567141240.768917928385471"

------sinikael-?=_2-16771567141240.768917928385471
Content-Type: text/plain
Content-Transfer-Encoding: quoted-printable

ci.tests.gmail@flowcrypt.test has sent you a password-encrypted email. =
Follow this link to open it: https://flowcrypt.com/shared-tenant-fes/messag=
e/6da5ea3c-d2d6-4714-b15e-f29c805e5c6a


------sinikael-?=_2-16771567141240.768917928385471
Content-Type: text/html; format=flowed
Content-Transfer-Encoding: 7bit

ci.tests.gmail@flowcrypt.test&nbsp;has&nbsp;sent&nbsp;you&nbsp;a&nbsp;password-encrypted&nbsp;email 
<a 
href="https:&#x2F;&#x2F;flowcrypt.com&#x2F;shared-tenant-fes&#x2F;message&#x2F;6da5ea3c-d2d6-4714-b15e-f29c805e5c6a" 
style="padding: 2px 6px; background: #2199e8; color: #fff; display: 
inline-block; text-decoration: none;">Click here to Open 
Message</a><br/><br/>Alternatively copy and paste the following link: 
https:&#x2F;&#x2F;flowcrypt.com&#x2F;shared-tenant-fes&#x2F;message&#x2F;6da5ea3c-d2d6-4714-b15e-f29c805e5c6a<br/><br/>
------sinikael-?=_2-16771567141240.768917928385471--

------sinikael-?=_1-16771567141240.768917928385471
Content-Type: application/octet-stream; name=
Content-Description: PGP/MIME version identification
Content-Disposition: attachment
X-Attachment-Id: f_hUZarNUkvTpFCPxMJlkVwNSTLFooDv@flowcrypt
Content-Id: <f_hUZarNUkvTpFCPxMJlkVwNSTLFooDv@flowcrypt>
Content-Transfer-Encoding: 7bit

Version: 1
------sinikael-?=_1-16771567141240.768917928385471
Content-Type: application/octet-stream; name=encrypted.asc
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename=encrypted.asc
X-Attachment-Id: f_PaOmzjmpnaCtBXpoOULZkcwPTctywH@flowcrypt
Content-Id: <f_PaOmzjmpnaCtBXpoOULZkcwPTctywH@flowcrypt>
Content-Transfer-Encoding: 7bit

-----BEGIN PGP MESSAGE-----
Version: FlowCrypt Email Encryption 8.4.2
Comment: Seamlessly send and receive encrypted email

wV4DeWfgCtVtdnoSAQdAToEMKRQZ/9tcvsVN52aREhcF+GQimeIFVkio2Oh1
oycwemHoU+s+VisjHWTDi8/bw63gVNR38xo1hdqUtDuG5vQG0hyvi6dvU6Il
JEoo+CYN0sHaAR+FTcnU4o0r2sv1HzAzvIc/nnMoWzsd7ffbdevklw6ByMrp
QsfuiDXdiM63D1ESh4fIWshg6H/3JcZJ/cmwJMSyLdBLmDdy6D7ZLBKNLrxA
lmMgEzlQ9Mgb9s4dAZ2AXmIcBlgZXr3IA9lxTmazowFHr3hQii/N4snxHa9Y
lP9EkWoHfsqaAvokDZSHLN/PWNDyEpXrJEHG8YTeVvL7eSCvCIfgk0E0AOYY
fuLwyCm6t1wPSjMC6l7rU0EiDms8a4c9T3YG8jOrCalh+WJXGpQbb9togEpo
Dz6unFD6TV9AUjeyzH1fFcL/SqZjzmeebNsO9utvLoEGG4e9RFmwL9rrdvh8
srbS0pPjVSwaz2EBvmXoK6WbCLVSWQBfmmA80rk8xqv4TIjAWW5G2rPqtLhM
BeN6UKOMjb7TMlLC7FhG/dI22+lcmCawI5H2cYi178jCygBpmNAz/tbkGlU+
Rki5ADqtXcN7Kf99CfHR9Q9qyeUQzA6qUgfpgb0msz1Dg1VX2Tc2FCTNom9B
4UsoA0WjVge8WgTK1dLVZ3M0BaZKgwDvJnUdCmcPrb1PUk1hvh1D46Nvv7FP
FQAF8gxYK+RdzgV3gB0vno/oWfAJx5t91vuZa5pOfzZiq5ULX+3IYd/U7r/L
DZbuPmPuJuO/uhPoF9jn93us4Kaf1f37SRQnpvGVOV82ZWJJQQJ9LciEm/RJ
2C1rJjMZugWeuDVkL1jeeoLRsoJyK7NnkmtRFUlleyrrARLeT3BiYTXmhOCQ
u63Y+ubkTKSlsj4wu6FMhi8WdVHwp98EIGBMiS8vQGOTheK3/4snZebQuGpm
qsOjlvFFDSK8Od03PwztxLRQkCQ/qHNo+e5vQc4/qddl2hLjJsS2ZKfVoz/e
=J+OL
-----END PGP MESSAGE-----
```

The format is totally different from Android's and we don't attach files

**Review by sosnovsky — APPROVED** [review]

**Pull request merged**
