### PR TITLE
Add svg icon for revoked keys

### LINKED ISSUE #3662: svg icon for revoked keys
@limonte could you add a similar icon into svgs that has maybe a stop sign? Or exclamation mark?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/3658#discussion_r636917911_

### PR DESCRIPTION
**Pull request by limonte**
close #3662

image

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Great! Can the color of the icon be controlled with css color (eg to make it white on non-white background?)

**Review by tomholub — APPROVED** [review]

**Comment by limonte** [comment]
> Great! Can the color of the icon be controlled with css color (eg to make it white on non-white background?)

No, AFAIK. In order to make it customizable there shouldn't be hardcoded `fill="#ff5576"`. But I believe this icon should be good for most backgrounds:

image

**Comment by tomholub** [comment]
I'd like to put it on an orange background :-) and possibly red. Sorry for not mentioning. could you make it customizable?

**Comment by limonte** [comment]
> I'd like to put it on an orange background :-) and possibly red. Sorry for not mentioning. could you make it customizable?

Sure! I'll submit another PR related to this issue, no need in additional issue.

**Comment by limonte** [comment]
CSS techniques for changing SVG fill color exist, but they are a bit complicated for such a small thing. In order to keep it simple, should I just submit another icon with `fill="white"`?

**Comment by tomholub** [comment]
Actually it's ok to have a separate white one. With one red and one white, we can really cover all scenarios I think.

**Pull request merged**
