### PR TITLE
#5296 Investigate tests calling live services

### LINKED ISSUE #5296: 404 when calling client-configuration?domain=flowcrypt.dev during tests on PROD?
title: Error
message: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForward
url: chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.htm?account_email=ci.tests
line: 377
column: 15
environment: chrome:ex:fork
build type: consumer 

This actually happens in our CI. Please can you check which test causes this? It's weird that it calls PROD FES, maybe it's a live gmail test?

If this is a mock test, we should fix that, it should not be calling live services.

If it is a live test, we'll decide what to do with it once we see the test.

```
Error: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForward
at Catch.nameAndDetailsAsException (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:377:15)
at Catch.report (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:103:34)
at Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/settings.js:390:27)
at async SettingsView.<anonymous> (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.js:198:28)


details:
[typeof:object:[object Object]] {"result":"Error","error":"Grant successful but error accessing fc account: Error: Not Found: 404 when GET-ing https://flowcrypt.com/shared-tenant-fes/api/v1/client-configuration?domain=flowcrypt.dev (no body): -> Missing client configuration for domain flowcrypt.dev","acctEmail":"ci.tests."}

### Catch.reportErr calling stack ###
# at Catch.formatExceptionForReport (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:273:90)
# at Catch.onErrorInternalHandler (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:81:29)
# at Catch.reportErr (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:97:18)
# at Catch.report (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:103:18)
# at Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/settings.js:390:27)
# at async SettingsView.<anonymous> (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.js:198:28)
#
# url: chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.htm?account_email=ci.tests.gmail@flowcrypt.dev
#
######################
```

### PR DESCRIPTION
**Pull request by martgil**
This PR is only used for investigating running tests that call live services.

close #5296 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
Thanks, Roma - I'm sorry for the disturbance.

**Comment by sosnovsky** [comment]
I checked exceptions list and didn't find any occurrence of this issue since 8.5.0 extension release, maybe earlier there were some issues on FES side which lead to 404 error for `flowcrypt.dev` client configuration, but they were fixed in later FES releases. So for now this issue seems to be fixed and nothing needs to be done here.

**Comment by martgil** [comment]
Thanks for your reply, @sosnovsky. That is also on my mind. Can we close this PR (and #5296)?

**Comment by sosnovsky** [comment]
> Thanks for your reply, @sosnovsky. That is also on my mind. Can we close this PR (and #5296)?

Yes, let's close it for now, as in the latest builds mentioned issue didn't occur.

**Pull request closed without merging**
