### PR TITLE
Removed bulkExport and UserMessages

### LINKED ISSUE #2753: transition mock data from external repo into this repo
Our existing system downloads mock data in bulk from https://github.com/FlowCrypt/flowcrypt-bin/tree/master/gmail-mock-data

This is not convenient when team members want to add more tests, and I'd like to get rid of it.

Instead I'd like to use a newer mechanism - storing needed messages in `exported-messages` folder.

Relevant code:
```
  /**
   * This is the proper way to add messages to mock api for testing:
   *   1) log into flowcrypt.compatibility@gmail.com
   *   2) go to Settings -> Inbox and find your message
   *   3) click "download api export"
   *   4) save the json file to exported-messages folder
   */
  private exportedMsgsPath = './test/source/mock/google/exported-messages/';

  /**
   * The original way was to export whole account at once, encrypt it and download it later.
   * There are several problems with this approach:
   *  - need to re-export whole inbox each time we want to add a message
   *  - many messages are included that are not needed for testing
   *  - lack of visibility or ability to easily edit messages
   *  - messages may contain sensitive information, so we cannot freely include them
   *      in the repo - they are encrypted and new developers cannot run tests without
   *      a test-secrets.json file, which is inconvenient
   *  This list of message ids will be skipped when importing the bulk import, instead
   *    they will be imported from the newer mechanism - exported-messages folder.
   *  We will be transferring used messages to this mechanism one by one, until there
   *    are no more messages in the bulk import, at which point we can remove this prop
   *    as well as all functionality that relates to it.
   */
  private skipBulkImportMessages = ['171d138c8750863b'];
```

A thing to note is that the old mechanism just exported the whole inbox, even messages we don't need. These are bulky. For `exported-messages` we should only store mocks we are actually using.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
Closes #2753

### CODE REVIEW

**Review by tomholub — COMMENTED** [review]
Looking forward! :)

**Review by tomholub — COMMENTED** [review]
:+1:

**Review by tomholub — COMMENTED** [review]
:+1:

**Review by tomholub — COMMENTED** [review]
No small task, but you're getting there :+1:

**Comment by rrrooommmaaa** [comment]
@tomholub Interestingly, looks like composer doesn't search for contacts in Drafts.
As I moved messages tagged with `DRAFT` label to DATA[acctEmail].drafts, the test `compose - can load contact based on name different from email` started to fail. Turns out `FirstName` only appears in on message labeled as DRAFT. Actually, in gmail Flowcrypt also doesn't recognize this recipient. Should this be filed as a bug in contacts search?
And how do we fix this PR? Should we create a non-draft message to search for `FirstName`?

**Comment by tomholub** [comment]
> @tomholub Interestingly, looks like composer doesn't search for contacts in Drafts.
> As I moved messages tagged with `DRAFT` label to DATA[acctEmail].drafts, the test `compose - can load contact based on name different from email` started to fail. Turns out `FirstName` only appears in a single message labeled as DRAFT. Actually, in gmail Flowcrypt also doesn't recognize this recipient. Should this be filed as a bug in contacts search?
> And how do we fix this PR? Should we create a non-draft message to search for `FirstName`?

It's supposed to search in sent messages, not in drafts.

Therefore it seems behavior of the code is correct (if it can recognize sent messages, but not drafts), and therefore the message should be moved to sent folder (and maybe slightly updated), which should fix the test.

**Review by tomholub — APPROVED** [review]
All looks good if tests pass

**Comment by rrrooommmaaa** [comment]
5 messages still have missing or empty "attachments" property in their JSON while they do have "attachmentId"s . This may affect future testing. Do you suggest to leave as it is or fill them just in case?

**Comment by tomholub** [comment]
I think ok to leave them. Most commonly, when we need to test a new message-related thing, it will come with a newly exported message to test on.

**Pull request merged**
